### ISSUE TITLE
Definition of "refdist"

### ISSUE THREAD

**Issue by tgong1** [spiralgenetics/truvari#1]
Hi,

I'd like to ask for more detail of the definition of "refdist".
The first step in methodology is:
Fetch CompCalls overlapping within *refdist*.

I found it is not required that 
base_call_start - redist < comp_call_start < base_call_start + refdist AND
base_call_end - redist < comp_call_end < base_call_end + refdist

Does this step fetch all CompCalls having at least 1pb overlapping within base_call_start - refdist to base_call_end + refdist?

Thank you very much!

**Comment by ACEnglish** [comment]
Correct, overlaps is defined as any calls with at least one overlapping base, so all comp calls with at least 1bp overlapping would be compared for potential matching.
