### ISSUE TITLE
when SVs without SVLEN in vcf file

### ISSUE THREAD

**Issue by xiaozhangzaq** [spiralgenetics/truvari#12]
which version of pyvcf package do you use, about the line 226 and 228, i should fix it as the left, otherwise it will report error  ( the left is i fixed, the right is the original code)
![truvari_bug](https://user-images.githubusercontent.com/19809536/48744807-bd9ff000-eca3-11e8-994e-051218002832.png)

**Comment by ACEnglish** [comment]
Thanks! Change incorporated.
