### ISSUE TITLE
update to include v0.6 in readme

### ISSUE THREAD

**Issue by jzook** [spiralgenetics/truvari#13]
It would be good to update the GIAB report part of the readme to reflect that it works with v0.6.  You could change this:

> This currently only works with GIAB SV v0.5. Work will need to be done to ensure Truvari can parse future GIAB SV releases.

> ftp://ftp-trace.ncbi.nlm.nih.gov/giab/ftp/data/AshkenazimTrio/analysis/NIST_UnionSVs_12122017/

to this:

> While truvari can use other benchmark sets, this formatted report currently only works with GIAB SV v0.5 and v0.6. Work will need to be done to ensure Truvari can parse future GIAB SV releases.

> ftp://ftp-trace.ncbi.nlm.nih.gov/giab/ftp/data/AshkenazimTrio/analysis/NIST_SVs_Integration_v0.6/

**Comment by ACEnglish** [comment]
Good catch! Thanks!
