### ISSUE TITLE
Question about SVTYPE=INS comparison

### ISSUE THREAD

**Issue by MaestSi** [spiralgenetics/truvari#14]
Dear Truvari developers,
I would like to use your tool to compare a set of 'comp' calls to a set of 'base' calls for NA24385 sample ([ftp://ftp-trace.ncbi.nlm.nih.gov/giab/ftp/data/AshkenazimTrio/analysis/NIST_SVs_Integration_v0.6/HG002_SVs_Tier1_v0.6.vcf.gz](url)).
I read that HG002_SVs_Tier1_v0.6.vcf.gz contains only SVTYPE=DUP and SVTYPE=INS variants, however there is a field named REPTYPE which gives further information about the type of variant. I saw that SVTYPE=INS variants may have REPTYPE=DUP value. So, my questions are:

- If I want to benchmark insertion calls from a SV-caller whose VCF file splits the INS structural variants over SVTYPE=INS and SVTYPE=DUP types (or gives only SVTYPE=DUP variants), is Truvari only going to consider SVTYPE=INS variants for insertions comparisons or is it able to manage different types of variants annotations, if these are compliant to the VCF format? 

- If a SV-caller I want to benchmark produces a VCF file with many other SVTYPEs (as INV, BND, ...) along with DEL and INS, are those going to decrease the overall precision or are they just going to be ignored? In other words, is it better to grep only the "interesting" lines from the 'comp' calls VCF or is it indifferent?
 
Thanks

**Comment by ACEnglish** [comment]
I've updated the code's documentation to more clearly explain how type comparisons are performed.

```
def same_variant_type(entryA, entryB):
    """
    returns if entryA svtype == entryB svtype

    How svtype is determined:
    - Starts by trying to use INFO/SVTYPE
    - If SVTYPE is unavailable, Infer if netry is a insertion or deletion by
      looking at the REF/ALT sequence size differences
    - If REF/ALT sequences are not available, try to parse the <INS>, <DEL>, etc in the ALT column.
    - Otherwise, rely on vcf.model._Record.var_subtype
    """
```

If you want your 'DUP' types to be compared with 'INS' types, consider subsetting the base/comp VCFs to only entries of a certain type, then use `--typeignore` to have truvari skip running the above method.

**Comment by MaestSi** [comment]
Thank you, just 2 additional questions:

- As for the --sizemin and --sizefilt parameters, since INS tipically have starting and ending coordinate that are identical, should I modify the default values (--sizemin 50 --sizefilt 30) ?
- Is Truvari able to parse AVGLEN (from Parliament2 output) for inferring the INS size, in order to perform a comparison on non-sequence-resolved calls (--pctsim 0)?
