### ISSUE TITLE
Latest intervaltree API update breaks on current truvari code 

### ISSUE THREAD

**Issue by ctsa** [spiralgenetics/truvari#16]
Hi, Thanks for releasing truvari. I just installed truvari according to the readme and got the following error the first time I ran it:

    AttributeError: 'IntervalTree' object has no attribute 'search'

This looks like it is caused by a breaking API change in the intervaltree 3 release. I changed my installation to use:

    pip install intervaltree==2.1.0
    pip install pyvcf python-Levenshtein progressbar2 pysam pyfaidx

...instead, and everything seems to be working as documented now. Could you update the README installation instructions to reflect this change?

**Comment by nnariai** [comment]
I encountered the same error, and the problem was resolved as described by @ctsa . It would be great if you can update the README installation instruction. Thanks!
