### ISSUE TITLE
Question about SVTYPE=INS - part2

### ISSUE THREAD

**Issue by MaestSi** [spiralgenetics/truvari#18]
Dear Truvari developers,
as suggested answering a previous question of mine, since I want to compare DUP/INS 'calls' to INS from 'base' GIAB vcf file, I subset the base/comp VCFs to only entries of a certain type, then used --typeignore to avoid all DUP calls being considered as False Positives because of non-matching SV type.
My additional questions are:
- As for the --sizemin and --sizefilt parameters, since INS tipically have starting and ending coordinate that are identical, should I modify the default values (--sizemin 50 --sizefilt 30) ?

- Is Truvari able to parse AVGLEN (from Parliament2 output) for inferring the INS size, in order to perform a comparison of non-sequence-resolved calls (--pctsim 0)?

**Comment by ACEnglish** [comment]
Hello,

I've updated the code's documentation to more clearly explain how size is determined

```
def get_vcf_entry_size(entry):
    """
    returns the size of the variant.

    How size is determined:
    - Starts by trying to use INFO/SVLEN
    - If SVLEN is unavailable and ALT field is an SV (e.g. <INS>, <DEL>, etc),
      use abs(vcf.model._Record.start - vcf.model._Record.end). The INFO/END
      tag needs to be available, especially for INS.
    - Otherwise, return the size difference of the sequence resolved call using
      abs(len(vcf.model._Record.REF) - len(str(vcf.model._Record.ALT[0])))
    """
```
Therefore, you could rename or duplicate the AVGLEN field to SVLEN.
As for the `--sizemin` and `--sizefilt`, presumably the default values will work for your comparison.

**Comment by MaestSi** [comment]
Thank you very much.
