### ISSUE TITLE
Self-comparison not giving 100% F1 score value

### ISSUE THREAD

**Issue by MaestSi** [spiralgenetics/truvari#19]
Dear truvari developers,
in order to see if I had correctly understood how to use Truvari, I tried passing as 'base' and as 'call' the same VCF file. Obviously, I was expecting to get a 100% recall and 100% precision, but that was not the case.
In particular, I tried using a subset of the HG002_SVs_Tier1_v0.6.vcf file, including only PASS deletions (grep "SVTYPE=DEL" | grep $’\tPASS$’\t’) as base, and HG002_SVs_Tier1_v0.6.vcf file, including only deletions (grep "SVTYPE=DEL" and --passonly flag) as call.
Since I am interested in using Truvari to benchmark some callers on hg38 reference, I also did a lift-over of the HG002_SVs_Tier1_v0.6.vcf file and of the HG002_SVs_Tier1_v0.6.bed file, and repeated the analysis.

This was my command for analysis on hg19:
`/mnt/cifs01/simone/software/truvari/truvari.py -b /mnt/cifs01/simone/NA24385/GIAB/hg19/HG002_SVs_Tier1_v0.6_DELs_PASS.vcf.gz -c /mnt/cifs01/simone/NA24385/GIAB/hg19/prova/HG002_SVs_Tier1_v0.6_DELs.vcf.gz -o /mnt/cifs01/simone/NA24385/GIAB/hg19/prova/TRUVARI_DELs_PASS_SIZEMIN50_SIZEMAX1000000000 --includebed /mnt/cifs01/simone/NA24385/GIAB/hg19/HG002_SVs_Tier1_v0.6.bed --passonly --pctsim 0 --pctovl 0.0 --refdist 2000 --sizemin 50 --sizemax 1000000000 --giabreport -f /mnt/cifs01/simone/Whole_genome/ucsc.hg19.fasta`

And these were the results (as expected):

> {
>     "FP": 0,
>     "f1": 1.0,
>     "base gt filtered": 0,
>     "precision": 1.0,
>     "TP-call": 4203,
>     "call cnt": 4203,
>     "base size filtered": 0,
>     "FN": 0,
>     "TP-base": 4203,
>     "base cnt": 4203,
>     "recall": 1.0,
>     "call gt filtered": 0,
>     "call size filtered": 0
> }

 

While this was my command for analysis on hg38 after lift-over of VCF and bed files:
`/mnt/cifs01/simone/software/truvari/truvari.py -b /mnt/cifs01/basaglia/NA24385/GIAB_reference/HG002_SVs_Tier1_v0.6_hg38_chr_PASS_DELs.vcf.gz -c /mnt/cifs01/basaglia/NA24385/GIAB_reference/prova/HG002_SVs_Tier1_v0.6_hg38_chr_DELs.vcf.gz -o /mnt/cifs01/basaglia/NA24385/GIAB_reference/prova/TRUVARI_DELs_PASS_SIZEMIN50_SIZEMAX1000000000 --includebed /mnt/cifs01/basaglia/NA24385/GIAB_reference/HG002_SVs_Tier1_v0.6_hg38_chr.bed --passonly --pctsim 0 --pctovl 0.0 --refdist 2000 --sizemin 50 --sizemax 1000000000 --giabreport -f /mnt/cifs01/basaglia/Homo_sapiens_assembly38.fasta`

And these were the results:
> {
>     "FP": 141,
>     "f1": 0.8166449934980494,
>     "base gt filtered": 0,
>     "precision": 0.8166449934980494,
>     "TP-call": 628,
>     "call cnt": 769,
>     "base size filtered": 0,
>     "FN": 141,
>     "TP-base": 628,
>     "base cnt": 769,
>     "recall": 0.8166449934980494,
>     "call gt filtered": 0,
>     "call size filtered": 0
> }
> 

What am I missing?
At a visual inspection of tn.vcf and fp.vcf, it seems that the 141 records are the same. Is it a problem due to the 'chr' prefix in chromosome names?

Thanks in advance.
Simone

**Comment by MaestSi** [comment]
I tried removing the 'chr' prefix from the vcfs and from the bed, but the results didn't change.
This is the first FP:
`cat fp.vcf | grep -v "^#" | head -n 1`

> 1       150065842       HG3_Ill_SVrefine2DISCOVARDovetail_520   TCAAAAT T       20      PASS    END=150037898;SVTYPE=DEL;SVLEN=-56;ClusterIDs=HG2_Ill_Spiral_45:HG3_Ill_Spiral_835:HG3_PB_pbsv_861:HG2_PB_pbsv_847:HG2_Ill_breakscan11_104:HG4_PB_pbsv_850:HG4_PB_assemblyticsfalcon_1152:HG4_PB_SVrefine2PBcRDovetail_477:HG4_Ill_svaba_968:HG4_Ill_scalpel_725:HG4_Ill_manta_192:HG4_Ill_SVrefine2DISCOVARDovetail_584:HG4_Ill_Krunchall_1108:HG4_Ill_GATKHC_1253:HG4_Ill_GATKHCSBGrefine_564:HG4_Ill_250bpfermikitraw_1050:HG4_Ill_150bpfermikitraw_994:HG4_CG_vcfBeta_519:HG4_10X_allpass_133:HG3_PB_assemblyticsfalcon_1156:HG3_PB_SVrefine2PBcRDovetail_500:HG3_Ill_svaba_995:HG3_Ill_scalpel_814:HG3_Ill_manta_166:HG3_Ill_SVrefine2DISCOVARDovetail_520:HG3_Ill_Krunchall_1093:HG3_Ill_GATKHC_1333:HG3_Ill_GATKHCSBGrefine_530:HG3_Ill_250bpfermikitraw_1040:HG3_Ill_150bpfermikitraw_981:HG3_CG_vcfBeta_440:HG3_10X_allpass_154:HG2_PB_SVrefine2PB10Xhap12_695:HG2_PB_SVrefine2Falcon2Bionano_137:HG2_PB_SVrefine2Falcon1plusDovetail_578:HG2_Ill_svaba_969:HG2_Ill_scalpel_747:HG2_Ill_manta_221:HG2_Ill_SpiralSDKrefine_771:HG2_Ill_SVrefine2DISCOVARplusDovetail_651:HG2_Ill_Krunchall_1062:HG2_Ill_GATKHC_1273:HG2_Ill_GATKHCSBGrefine_534:HG2_Ill_250bpfermikitraw_1050:HG2_Ill_150bpfermikitraw_943:HG2_CG_vcfBeta_469:HG2_10X_SVrefine210Xhap12_642:HG4_Ill_Spiral_67;NumClusterSVs=48;ExactMatchIDs=HG2_10X_SVrefine210Xhap12_642:HG2_CG_vcfBeta_469:HG2_Ill_150bpfermikitraw_943:HG2_Ill_250bpfermikitraw_1050:HG2_Ill_GATKHCSBGrefine_534:HG2_Ill_GATKHC_1273:HG2_Ill_Krunchall_1062:HG2_Ill_SVrefine2DISCOVARplusDovetail_651:HG2_Ill_SpiralSDKrefine_771:HG2_Ill_manta_221:HG2_Ill_scalpel_747:HG2_Ill_svaba_969:HG2_PB_SVrefine2Falcon1plusDovetail_578:HG2_PB_SVrefine2Falcon2Bionano_137:HG2_PB_SVrefine2PB10Xhap12_695:HG3_10X_allpass_154:HG3_CG_vcfBeta_440:HG3_Ill_150bpfermikitraw_981:HG3_Ill_250bpfermikitraw_1040:HG3_Ill_GATKHCSBGrefine_530:HG3_Ill_GATKHC_1333:HG3_Ill_Krunchall_1093:HG3_Ill_SVrefine2DISCOVARDovetail_520:HG3_Ill_manta_166:HG3_Ill_scalpel_814:HG3_Ill_svaba_995:HG3_PB_SVrefine2PBcRDovetail_500:HG3_PB_assemblyticsfalcon_1156:HG4_10X_allpass_133:HG4_CG_vcfBeta_519:HG4_Ill_150bpfermikitraw_994:HG4_Ill_250bpfermikitraw_1050:HG4_Ill_GATKHCSBGrefine_564:HG4_Ill_GATKHC_1253:HG4_Ill_Krunchall_1108:HG4_Ill_SVrefine2DISCOVARDovetail_584:HG4_Ill_manta_192:HG4_Ill_scalpel_725:HG4_Ill_svaba_968:HG4_PB_SVrefine2PBcRDovetail_477:HG4_PB_assemblyticsfalcon_1152:HG4_PB_pbsv_850;NumExactMatchSVs=42;ClusterMaxShiftDist=0.0350877192982;ClusterMaxSizeDiff=0.0350877192982;ClusterMaxEditDist=0.0350877192982;PBcalls=10;Illcalls=32;TenXcalls=3;CGcalls=3;PBexactcalls=8;Illexactcalls=28;TenXexactcalls=3;CGexactcalls=3;HG2count=18;HG3count=15;HG4count=15;NumTechs=4;NumTechsExact=4;DistBack=54590;DistForward=-47;DistMin=-47;DistMinlt1000=TRUE;MultiTech=TRUE;MultiTechExact=TRUE;sizecat=50to99;DistPASSHG2gt49Minlt1000=FALSE;DistPASSMinlt1000=FALSE;MendelianError=FALSE;HG003_GT=1/1;HG004_GT=1/1;BREAKSIMLENGTH=10;REFWIDENED=1:150037843-150037908;REPTYPE=SIMPLEDEL;TRall=TRUE;TRgt100=FALSE;TRgt10k=FALSE;segdup=FALSE  GT:GTcons1:PB_GT:PB_REF:PB_ALT:PBHP_GT:PB_REF_HP1:PB_ALT_HP1:PB_REF_HP2:PB_ALT_HP2:TenX_GT:TenX_REF_HP1:TenX_ALT_HP1:TenX_REF_HP2:TenX_ALT_HP2:ILL250bp_GT:ILL250bp_REF:ILL250bp_ALT:ILLMP_GT:ILLMP_REF:ILLMP_ALT:BNG_LEN_DEL:BNG_LEN_INS:nabsys_svm      1/1:1/1:./.:6:50:1/1:0:22:2:8:1/1:0:24:0:15:1/1:0:64:./.:.:.:.:.:.
>

And this is the first FN.
`cat fn.vcf | grep -v "^#" | head -n 1`

> 1       150065842       HG3_Ill_SVrefine2DISCOVARDovetail_520   TCAAAAT T       20      PASS    END=150037898;SVTYPE=DEL;SVLEN=-56;ClusterIDs=HG2_Ill_Spiral_45:HG3_Ill_Spiral_835:HG3_PB_pbsv_861:HG2_PB_pbsv_847:HG2_Ill_breakscan11_104:HG4_PB_pbsv_850:HG4_PB_assemblyticsfalcon_1152:HG4_PB_SVrefine2PBcRDovetail_477:HG4_Ill_svaba_968:HG4_Ill_scalpel_725:HG4_Ill_manta_192:HG4_Ill_SVrefine2DISCOVARDovetail_584:HG4_Ill_Krunchall_1108:HG4_Ill_GATKHC_1253:HG4_Ill_GATKHCSBGrefine_564:HG4_Ill_250bpfermikitraw_1050:HG4_Ill_150bpfermikitraw_994:HG4_CG_vcfBeta_519:HG4_10X_allpass_133:HG3_PB_assemblyticsfalcon_1156:HG3_PB_SVrefine2PBcRDovetail_500:HG3_Ill_svaba_995:HG3_Ill_scalpel_814:HG3_Ill_manta_166:HG3_Ill_SVrefine2DISCOVARDovetail_520:HG3_Ill_Krunchall_1093:HG3_Ill_GATKHC_1333:HG3_Ill_GATKHCSBGrefine_530:HG3_Ill_250bpfermikitraw_1040:HG3_Ill_150bpfermikitraw_981:HG3_CG_vcfBeta_440:HG3_10X_allpass_154:HG2_PB_SVrefine2PB10Xhap12_695:HG2_PB_SVrefine2Falcon2Bionano_137:HG2_PB_SVrefine2Falcon1plusDovetail_578:HG2_Ill_svaba_969:HG2_Ill_scalpel_747:HG2_Ill_manta_221:HG2_Ill_SpiralSDKrefine_771:HG2_Ill_SVrefine2DISCOVARplusDovetail_651:HG2_Ill_Krunchall_1062:HG2_Ill_GATKHC_1273:HG2_Ill_GATKHCSBGrefine_534:HG2_Ill_250bpfermikitraw_1050:HG2_Ill_150bpfermikitraw_943:HG2_CG_vcfBeta_469:HG2_10X_SVrefine210Xhap12_642:HG4_Ill_Spiral_67;NumClusterSVs=48;ExactMatchIDs=HG2_10X_SVrefine210Xhap12_642:HG2_CG_vcfBeta_469:HG2_Ill_150bpfermikitraw_943:HG2_Ill_250bpfermikitraw_1050:HG2_Ill_GATKHCSBGrefine_534:HG2_Ill_GATKHC_1273:HG2_Ill_Krunchall_1062:HG2_Ill_SVrefine2DISCOVARplusDovetail_651:HG2_Ill_SpiralSDKrefine_771:HG2_Ill_manta_221:HG2_Ill_scalpel_747:HG2_Ill_svaba_969:HG2_PB_SVrefine2Falcon1plusDovetail_578:HG2_PB_SVrefine2Falcon2Bionano_137:HG2_PB_SVrefine2PB10Xhap12_695:HG3_10X_allpass_154:HG3_CG_vcfBeta_440:HG3_Ill_150bpfermikitraw_981:HG3_Ill_250bpfermikitraw_1040:HG3_Ill_GATKHCSBGrefine_530:HG3_Ill_GATKHC_1333:HG3_Ill_Krunchall_1093:HG3_Ill_SVrefine2DISCOVARDovetail_520:HG3_Ill_manta_166:HG3_Ill_scalpel_814:HG3_Ill_svaba_995:HG3_PB_SVrefine2PBcRDovetail_500:HG3_PB_assemblyticsfalcon_1156:HG4_10X_allpass_133:HG4_CG_vcfBeta_519:HG4_Ill_150bpfermikitraw_994:HG4_Ill_250bpfermikitraw_1050:HG4_Ill_GATKHCSBGrefine_564:HG4_Ill_GATKHC_1253:HG4_Ill_Krunchall_1108:HG4_Ill_SVrefine2DISCOVARDovetail_584:HG4_Ill_manta_192:HG4_Ill_scalpel_725:HG4_Ill_svaba_968:HG4_PB_SVrefine2PBcRDovetail_477:HG4_PB_assemblyticsfalcon_1152:HG4_PB_pbsv_850;NumExactMatchSVs=42;ClusterMaxShiftDist=0.0350877192982;ClusterMaxSizeDiff=0.0350877192982;ClusterMaxEditDist=0.0350877192982;PBcalls=10;Illcalls=32;TenXcalls=3;CGcalls=3;PBexactcalls=8;Illexactcalls=28;TenXexactcalls=3;CGexactcalls=3;HG2count=18;HG3count=15;HG4count=15;NumTechs=4;NumTechsExact=4;DistBack=54590;DistForward=-47;DistMin=-47;DistMinlt1000=TRUE;MultiTech=TRUE;MultiTechExact=TRUE;sizecat=50to99;DistPASSHG2gt49Minlt1000=FALSE;DistPASSMinlt1000=FALSE;MendelianError=FALSE;HG003_GT=1/1;HG004_GT=1/1;BREAKSIMLENGTH=10;REFWIDENED=1:150037843-150037908;REPTYPE=SIMPLEDEL;TRall=TRUE;TRgt100=FALSE;TRgt10k=FALSE;segdup=FALSE;NumNeighbors=0;NumThresholdNeighbors=0   GT:GTcons1:PB_GT:PB_REF:PB_ALT:PBHP_GT:PB_REF_HP1:PB_ALT_HP1:PB_REF_HP2:PB_ALT_HP2:TenX_GT:TenX_REF_HP1:TenX_ALT_HP1:TenX_REF_HP2:TenX_ALT_HP2:ILL250bp_GT:ILL250bp_REF:ILL250bp_ALT:ILLMP_GT:ILLMP_REF:ILLMP_ALT:BNG_LEN_DEL:BNG_LEN_INS:nabsys_svm        1/1:1/1:./.:6:50:1/1:0:22:2:8:1/1:0:24:0:15:1/1:0:64:./.:.:.:.:.:.
> 
Although they seem to be identical, they don't match according to Truvari.

**Comment by ACEnglish** [comment]
The only variable you haven't accounted for is what the liftover procedure may have done to the variants. Are you certain that liftover didn't alter the data at all? 
If you'd like more information about what Truvari is doing internally as it goes through variant comparison, you can use the `--debug` flag to get very verbose logs.
Here's a code grep of debug lines it may log.
```python
            logging.debug("Comparing %s %s", str(base_entry), str(comp_entry))
                logging.debug("No match because comparison call already matched")
                logging.debug("%s is hom-ref", str(comp_entry))
                logging.debug("%s and %s are not the same genotype", str(base_entry), str(comp_entry))
                logging.debug("%s and %s are not the same SVTYPE", str(base_entry), str(comp_entry))
                logging.debug("%s and %s size similarity is too low (%f)", str(
                logging.debug("%s and %s overlap percent is too low (%f)", str(base_entry), str(comp_entry), ovl_pct)
                    logging.debug("%s and %s sequence similarity is too low (%f)", str(
            logging.debug("Picking from candidate matches:\n%s", "\n".join([str(x) for x in thresh_neighbors]))
            logging.debug("Best match is %s", str(match_entry))
            logging.debug("Matching %s and %s", str(base_entry), str(match_entry))
```
This may give you insight as to why your calls aren't put together.

-----
On second look, I think I see a possible side problem with the liftover. If you look at your example variant, it is a 56bp Deletion on grch37 but shrinks to a 6bp deletion after liftover (TCAAAAT -> T). However, the INFO/SVLEN is still at -56. These fields are used by Truvari. See #18 for details on how variant sizes are looked at. 
This doesn't exactly explain what's happening here, but should probably be fixed for completeness.

**Comment by MaestSi** [comment]
No, I am not certain lift-over didn't alter the data at all.
But my guess was that, in any case, the self comparison should have always returned a 100% match, since also in case there are some mistakes, those are there in both base and call files.
After the CrossMap liftover, which I had previously used, I also tried out Picard LiftoverVcf (which gave error) and finally NCBI Remap.
Also in the NCBI Remap lift-over I noticed that some discrepancies between SVLEN and `len(REF) - len(ALT)` were there.
Finally, I tried to substitute the ALT and REF sequences in the VCF with '.', in order to force Truvari to use SVLEN value.
Results didn't change consistently, also when using the --multimatch parameter.
Debug logs didn't provide me any further information.
Thanks,
Simone

**Comment by ACEnglish** [comment]
If you could provide me your liftover 38 vcf, I'd be happy to do some
further digging

**Comment by MaestSi** [comment]
The file is too big to be sent via Github or e-mail (about 140 MB).
However, I generated it adding the 'chr' prefix to all chromosomes (both in the header, in the first column and in the REFWIDENED field) and then doing a lift-over with the command:
`CrossMap.py vcf  hg19ToHg38.over.chain HG002_SVs_Tier1_v0.6_chr.vcf Homo_sapiens_assembly38.fasta HG002_SVs_Tier1_v0.6_hg38_chr.vcf`

**Comment by ACEnglish** [comment]
How about just a subset of the file? You already saw a chr1 call problem,
so just chr1 calls may suffice

**Comment by MaestSi** [comment]
Sure, here it is a part of the lited-over VCF file (only PASS DELs in chr1)
[HG002_SVs_Tier1_v0.6_hg38_chr1_PASS.vcf.txt](https://github.com/spiralgenetics/truvari/files/2914170/HG002_SVs_Tier1_v0.6_hg38_chr1_PASS.vcf.txt)
This was the command I used for Truvari self-comparison:
`python truvari.py -b HG002_SVs_Tier1_v0.6_hg38_chr1_PASS_DELs.vcf.gz -c HG002_SVs_Tier1_v0.6_hg38_chr1_PASS_DELs.vcf.gz -o test --includebed HG002_SVs_Tier1_v0.6_hg38_chr.bed --passonly --pctsim 0 --pctovl 0.0 --refdist 2000 --sizemin 50 --sizemax 1000000000 --giabreport -f Homo_sapiens_assembly38.fasta`
And these were the results I got:

> {
>     "FP": 43,
>     "f1": 0.2711864406779661,
>     "base gt filtered": 0,
>     "precision": 0.2711864406779661,
>     "TP-call": 16,
>     "call cnt": 59,
>     "base size filtered": 0,
>     "FN": 43,
>     "TP-base": 16,
>     "base cnt": 59,
>     "recall": 0.2711864406779661,
>     "call gt filtered": 0,
>     "call size filtered": 0
> }

In order to understand a little better if the problem was due to the VCF lift-over, I also tried this:

- Convert the hg19 reference file from VCF to 2 BED files (one for DELs and one for INSs)
- Perform a UCSC Liftover of the BED files and of the "includebed" BED file
- Convert the lifted-over hg38 VCF file to 2 BED files using the same script as before
- Perform a bedtools intersect comparison, filtering out entries outside of the includebed BED file

Results were approximately 100% matching. This might be a hint of "almost correct" VCF lift-over conversion, if we assume that BED files lift-over is correct.
What do you think about this?
Thanks,
Simone

**Comment by ACEnglish** [comment]
Hello,

I believe I've solved the problem.
During liftover, the INFO/END position of the VCF isn't updated in the calls. This messes up VCF entries' queries over the `--includebed` IntervalTree since the VCF contains hg38 start positions but hg37 end positions. Updating the INFO/END will give the expected results.

Here's a script to update the lifted-over vcf:
```python
#update_end script
import sys
import vcf

v = vcf.Reader(filename=sys.argv[1])
o = vcf.Writer(sys.stdout, v)

for entry in v:
    entry.INFO["END"] = entry.start + abs(entry.INFO["SVLEN"][0])
    o.write_record(entry)
```
Run the script over the provided VCF
```python update_end.py HG002_SVs_Tier1_v0.6_hg38_chr1_PASS_DELs.vcf.gz | bgzip > end_mv.vcf.gz && tabix -p vcf end_mv.vcf.gz```

Run Truvari:
```truvari.py -b end_mv.vcf.gz -c end_mv.vcf.gz -o test_mv --includebed HG02_Tier1_38.bed --passonly --pctsim 0 --pctovl 0 --refdist 2000 --sizemin 50 --sizemax 1000000000 --giabreport -f /reference/grch38_noalt_decoy/source.fasta```

> {
>     "FP": 0,
>     "f1": 1.0,
>     "base gt filtered": 0,
>     "precision": 1.0,
>     "TP-call": 308,
>     "call cnt": 308,
>     "base size filtered": 0,
>     "FN": 0,
>     "TP-base": 308,
>     "base cnt": 308,
>     "recall": 1.0,
>     "call gt filtered": 0,
>     "call size filtered": 0
> }

**Comment by MaestSi** [comment]
Perfect fix, thank you very much!
Simone
