### ISSUE TITLE
understanding "call cnt"

### ISSUE THREAD

**Issue by mpauper** [spiralgenetics/truvari#21]
Hello!

I am still new to using truvari, so I am still trying to fully comprehend what I see.

One thing I have encountered and is troubling me, is that I assumed that "call cnt" should be the number of records in the input VCF COMP file, however the two numbers would not match.

I found this in truvari.py, which explains why it would not match the number of records in the COMP vcf:
```
# call count is just of those used were used
stats_box["call cnt"] = stats_box["TP-base"] + stats_box["FP"]
```
Is this working as intended? Why would it not be "TP-call + FP" for instance? 

Thanks!

**Comment by ACEnglish** [comment]
With the recent changes to the `--multimatch` parameter, this number should be investigated. However, if you're not running with the `--multimatch`, then the number of TP-base and TP-comp calls are 1-to-1. Therefore, the 'call cnt' would be accurate. 
There are multiple reasons why this number may not match up to the number of entries in the vcf file. 1) Using the `--passonly` parameter and there are non-passing calls in the comparison vcf.
2) Calls falling outside of the `--sizemin` and `--sizemax` range
3) The `--no-ref` parameter would exclude vcf entries with a 0/0 or ./. genotype
4) Any calls falling outside of an `--includebed` would not added to the 'call cnt'
5) Comparison vcf entries with calls landing on reference contigs not represented in the base vcf's header would not be counted. E.g. your comparison vcf holds calls on GL12345.6, but the base vcf does not define that contig, those calls are not counted.

If you can show that none of these are causing the count differences you're seeing, please re-open this issue and let me know so I can dig in further.
