### ISSUE TITLE
Multimatch and MatchId

### ISSUE THREAD

**Issue by mpauper** [spiralgenetics/truvari#23]
Hello,

When inspecting the MatchId in tp-call.vcf and tp-base.vcf, I noticed that the set of tp-call match IDs is not equal to the set of tp-base match IDs. As a result, there are match IDs that are unique to tp-base and no easy to way to find what the call matches.

This is only observed when using --multimatch. 

Thanks!

**Comment by ACEnglish** [comment]
Could you provide an example of this happening with demonstrative input base/call vcf entries?
I'm not seeing this behavior on my side as shown below.

```bash
$ bcftools query -f "%INFO/MatchId\n" tp-base.vcf | sort -n | uniq > base_ids.txt
$ bcftools query -f "%INFO/MatchId\n" tp-call.vcf | sort -n | uniq > call_ids.txt
$ comm -3 base_ids.txt call_ids.txt 
# nothing returned because they're identical
```

**Comment by mpauper** [comment]
Can I send my input files to your e-mail?

**Comment by ACEnglish** [comment]
Before we go down that route, checkout develop of truvari and use add the `--network` parameter to your truvari run. 
I was was working on that feature previously for other reasons and may have lucked into already having your issue fixed.

**Comment by ACEnglish** [comment]
Multimatch parameter now redundantly outputs vcf entries with unique MatchIds.
