### ISSUE TITLE
TypeError: bad operand type for abs(): 'NoneType'

### ISSUE THREAD

**Issue by Macy-Zhao** [spiralgenetics/truvari#24]
hi,
I use it to compare pacbio sv  to nanopore sv, but I tried several times.
It bugged as below:
Traceback (most recent call last):
  File "/usr/local/bin/truvari", line 1047, in <module>
    run(sys.argv[1:])
  File "/usr/local/bin/truvari", line 788, in run
    sizeA = get_vcf_entry_size(base_entry)
  File "/usr/local/bin/truvari", line 271, in get_vcf_entry_size
    size = abs(entry.INFO["SVLEN"])
TypeError: bad operand type for abs(): 'NoneType'

what's meaning? How  I can change paramater?

my command line as below:
truvari -b ngm_Nanopore_human_ngmlr-0.2.3_mapped.bam.sniffles1kb_auto_s5_noalts.header.vcf.gz -c na12878_pacbio_mts_ngmlr-0.2.3_mapped.bam.sniffles1kb_auto_noalts.header.vcf.gz -o nanopore-vs-pacbio --reference ../GRCh38_full_analysis_set_plus_decoy_hla.fa --giabreport -t --debug --multimatch --pctsim=0

I have read code, there is a note """
returns the size of the variant.

How size is determined:
- Starts by trying to use INFO/SVLEN
- If SVLEN is unavailable and ALT field is an SV (e.g. <INS>, <DEL>, etc),
  use abs(vcf.model._Record.start - vcf.model._Record.end). The INFO/END
  tag needs to be available, especially for INS.
- Otherwise, return the size difference of the sequence resolved call using
  abs(len(vcf.model._Record.REF) - len(str(vcf.model._Record.ALT[0])))
"""
I'm currious about sv type, does it include  "<DUP/INS> and <INVDUP>"?  there are six types of sv in my file as below.
<DEL><DUP><DUP/INS><INS><INV><TRA><INVDUP>

Thanks for replying as soon as possible!

**Comment by Macy-Zhao** [comment]
I have read code, there is a note """
returns the size of the variant.

How size is determined:
- Starts by trying to use INFO/SVLEN
- If SVLEN is unavailable and ALT field is an SV (e.g. <INS>, <DEL>, etc),
  use abs(vcf.model._Record.start - vcf.model._Record.end). The INFO/END
  tag needs to be available, especially for INS.
- Otherwise, return the size difference of the sequence resolved call using
  abs(len(vcf.model._Record.REF) - len(str(vcf.model._Record.ALT[0])))
"""

I'm currious about sv type, does it include  "<DUP/INS>"?  there are six types of sv in my file as below.
<DEL>
<DUP>
<DUP/INS>
<INS>
<INV>
<TRA>

**Comment by ACEnglish** [comment]
Hi, sorry for the delay. My email notifications somehow were turned off.

It seems like you have a problem with your base-vcf `ngm_Nanopore_human_ngmlr-0.2.3_mapped.bam.sniffles1kb_auto_s5_noalts.header.vcf.gz` like perhaps you have entries where the INFO tag of SVLEN is blank? Could you inspect that vcf to ensure your every line has an actual value for SVLEN - e.g. ```bcftools query -f "%INFO/SVLEN\n" | sort -n | uniq -c```

As for <DUP/INS>, yes, any type should be parsed and those strings as-per the `get_vcf_variant_type` documentation
