### ISSUE TITLE
Filter/report by variant type

### ISSUE THREAD

**Issue by holtjma** [spiralgenetics/truvari#25]
Hello,

Is there an option to only compare variants of a certain type (i.e. "DEL") in the base/call set?  Alternatively, is there an option that will generate metrics by type? (i.e. precision/recall for DEL, INS, etc.).  I'm trying to see the metrics stratified by type.

Thanks

**Comment by ACEnglish** [comment]
Hello,
No, there is no option to restrict the type of calls considered in a comparison. However, If you're using GIAB v0.6 as your base-vcf, you can use --giabreport and a copy of the Google Sheet documented in the README to see type/size/etc stratification breakdowns of precision/recall.

If you're using non GIAB SVs as your base, then you'd need to extract/separate your base calls by type to see those subsetted summary.txt. Off the top of my head, a command would be something like:
```(zgrep # base.vcf.gz && bcftools query -f "%INFO/SVTYPE\t%LINE" base.vcf.gz | grep "^DEL" | cut -f2-) | bgzip > del_base.vcf.gz && tabix del_base.vcf.gz``` 
Note I just free-formed that command, so can't guarantee it'll work, but the structure is at least close.

Alternatively, you could do a little counting on your own and check the tp-base.vcf's number of DEL/INS ```bcftools query -f "%INFO/SVTYPE" tp-base.vcf | sort | uniq -c``` and calculate manually.
