### ISSUE TITLE
0 base variants

### ISSUE THREAD

**Issue by Ritu-Kundu** [spiralgenetics/truvari#26]
Hi there,

Firstly, thanks for this cool tool. I have two data-sets (Illumina PE reads) corresponding to two related individuals (humans). I want to compare their SVs which I created using Lumpy (and GrCh38 as the reference). When I run truvari with one of them as ground/base_calls and the other as compare_calls, I get everything 0 in summary.txt.

The log file of the run is attached.
[truvari_log.txt](https://github.com/spiralgenetics/truvari/files/3338459/truvari_log.txt)

**Comment by ACEnglish** [comment]
This is an odd error because the ground(comparision) calls are being parsed (`53944 call variants in total`), but the base vcf `individual1.sorted.vcf.gz` seems to be the problem. Can you inspect the two to see if there's any important differences?
