### ISSUE TITLE
getting a corrected VCF from truvari

### ISSUE THREAD

**Issue by sidharthgoel** [spiralgenetics/truvari#28]
Hi,
I wanted to know whether Truvari has the functionality to output a single 'corrected VCF' that shows for each position in the COMP, what is the true label for each position.

I've looked at all the output files it already produces, but I don't think it currently does this (nor with any of the flags). I think this feature would be somewhat similar to what hap.py does, which has the QUERY and TRUTH columns that show what the caller proposed versus what the truth shows.

It seems like Truvari would basically compute this internally at some point, but it just doesn't actually output it in any file (as far as I can tell).

**Comment by ACEnglish** [comment]
Hi,

There are already annotations in the output tp-base/tp-comp vcfs that allow one to identify which calls matched up.  All that's required is a post-process that leverages the MatchId INFO field which holds `##INFO=<ID=MatchId,Number=1,Type=Integer,Description="Truvari uid to help tie tp-base.vcf and tp-call.vcf entries together">`. e.g. tp-base.vcf has a call MatchId=1092 that was matched with  tp-call.vcf call with MatchId=1092.

Additionally, you may find the other INFO tags such as `StartDistance` and `EndDistance` useful.
