### ISSUE TITLE
ValueError: 'pysam.libcbcf.VariantFile.fetch' requires an index

### ISSUE THREAD

**Issue by tjiangHIT** [spiralgenetics/truvari#33]
Hi @ACEnglish ,
Thanks for your great SV benchmark tool **Truvari**.
Recently, I update my local truvari to the latest version 1.3.4, however, a **ValueError** arose as below:
>2019-11-09 06:16:52,814 [INFO] Running /home/tjiang/Tools/truvari/truvari/truvari -f /data/tjiang/SV_benchmark/ref/human_hs37d5.fasta -b /home/tjiang/HG002_SVs_Tier1_v0.6.vcf --includebed /data/tjiang/SV_benchmark/giab/HG002_SVs_Tier1_v0.6.bed -o bench-10x --passonly --giabreport -r 1000 -p 0 -c hg2_ont_10x_indel.vcf.gz
2019-11-09 06:16:52,814 [INFO] Params:
{
    "base": "/home/tjiang/HG002_SVs_Tier1_v0.6.vcf",
    "comp": "hg2_ont_10x_indel.vcf.gz",
    "output": "bench-10x",
    "reference": "/data/tjiang/SV_benchmark/ref/human_hs37d5.fasta",
    "giabreport": true,
    "debug": false,
    "prog": false,
    "refdist": 1000,
    "pctsim": 0.0,
    "pctsize": 0.7,
    "pctovl": 0.0,
    "typeignore": false,
    "gtcomp": false,
    "bSample": null,
    "cSample": null,
    "sizemin": 50,
    "sizefilt": 30,
    "sizemax": 50000,
    "passonly": true,
    "no_ref": false,
    "includebed": "/data/tjiang/SV_benchmark/giab/HG002_SVs_Tier1_v0.6.bed",
    "multimatch": false
}
2019-11-09 06:16:54,223 [INFO] Including 34830 bed regions
2019-11-09 06:16:54,223 [INFO] Creating call interval tree for overlap search
[W::vcf_parse] INFO 'BREAKPOINT_STD' is not defined in the header, assuming Type=String
[W::vcf_parse] INFO 'SVLEN_STD' is not defined in the header, assuming Type=String
2019-11-09 06:17:00,549 [INFO] 19009 call variants in total
2019-11-09 06:17:00,549 [INFO] 19008 call variants within size range (30, 50000)
2019-11-09 06:17:00,551 [INFO] Matching base to calls
Traceback (most recent call last):
  File "/home/tjiang/Tools/truvari/truvari/truvari", line 1051, in <module>
    main(sys.argv[1:])
  File "/home/tjiang/Tools/truvari/truvari/truvari", line 790, in main
    for pbarcnt, base_entry in enumerate(regions.iterate(vcf_base)):
  File "/home/tjiang/Tools/truvari/truvari/truvari", line 540, in iterate
    for entry in vcf_file.fetch(chrom, intv.begin, intv.end):
  File "pysam/libcbcf.pyx", line 4359, in pysam.libcbcf.VariantFile.fetch
ValueError: fetch requires an index

Do you have any ideas to help me fix this error?
Thank you very much!
tjiang

**Comment by ACEnglish** [comment]
Hi,
Could you make sure that your base vcf home/tjiang/HG002_SVs_Tier1_v0.6.vcf has
a tabix index home/tjiang/HG002_SVs_Tier1_v0.6.vcf.tbi

**Comment by tjiangHIT** [comment]
Hello @ACEnglish ,
Thanks for your reply!
I have three files in that folder, i.e., HG002_SVs_Tier1_v0.6.vcf, HG002_SVs_Tier1_v0.6.vcf.gz, HG002_SVs_Tier1_v0.6.vcf.gz.tbi.

**1. My first question is how to generate a **_vcf.tbi_** file.**
I just know tabix can used for generation of a **_vcf.gz.tbi_** file, which the vcf file should been compressed with bgzip.

**2. My second question is what the input base file is. _HG002_SVs_Tier1_v0.6.vcf_ or _HG002_SVs_Tier1_v0.6.vcf.gz_?**
In the older version of truvari, I used base.vcf.gz and comp.vcf.gz as input.
Now, when I use the same inputs as before, I will get this error:
>NotImplementedError: seek not implemented in files compressed by method 1

However, when I use base.vcf and comp.vcf.gz as input, one another error raises:
>ValueError: 'pysam.libcbcf.VariantFile.fetch' requires an index

Hope you can give me some advice!
Thanks.
tjiang

**Comment by ACEnglish** [comment]
Sorry, I mistyped. You want to generate a tabix file on the compressed vcf.gz file. Then use the vcf.gz file.

e.g.:
```bash
bgzip HG002_SVs_Tier1_v0.6.vcf
tabix HG002_SVs_Tier1_v0.6.vcf.gz
```
Also be sure you have your hg2_ont_10x_indel.vcf.gz.tbi generated.

**Comment by tjiangHIT** [comment]
Hi @ACEnglish ,
I don't think I have described my problem clearly.
For the version of 1.2 or before, I used truvari to perform benchmark successfully. For the version of 1.3 or higher, I used the same command line, but truvari broke down.
I think it was mainly caused by pysam:
>truvari -f /data/tjiang/SV_benchmark/ref/human_hs37d5.fasta -b /data/tjiang/SV_benchmark/giab/HG002_SVs_Tier1_v0.6.vcf.gz --includebed /data/tjiang/SV_benchmark/giab/HG002_SVs_Tier1_v0.6.bed  -o bench-5x --passonly --giabreport -r 1000 -p 0 -c hg2_ont_sniffles_5x_indel.vcf.gz
2019-11-11 07:13:32,814 [INFO] Params:
{
    "base": "/data/tjiang/SV_benchmark/giab/HG002_SVs_Tier1_v0.6.vcf.gz",
    "comp": "hg2_ont_sniffles_5x_indel.vcf.gz",
    "output": "bench-5x",
    "reference": "/data/tjiang/SV_benchmark/ref/human_hs37d5.fasta",
    "giabreport": true,
    "debug": false,
    "prog": false,
    "refdist": 1000,
    "pctsim": 0.0,
    "pctsize": 0.7,
    "pctovl": 0.0,
    "typeignore": false,
    "gtcomp": false,
    "bSample": null,
    "cSample": null,
    "sizemin": 50,
    "sizefilt": 30,
    "sizemax": 50000,
    "passonly": true,
    "no_ref": false,
    "includebed": "/data/tjiang/SV_benchmark/giab/HG002_SVs_Tier1_v0.6.bed",
    "multimatch": false
}
Traceback (most recent call last):
  File "/home/tjiang/miniconda3/envs/eva/bin/truvari", line 1044, in <module>
    main(sys.argv[1:])
  File "/home/tjiang/miniconda3/envs/eva/bin/truvari", line 706, in main
    vcf_base = pysam.VariantFile(args.base)
  File "pysam/libcbcf.pyx", line 4015, in pysam.libcbcf.VariantFile.__init__
  File "pysam/libcbcf.pyx", line 4274, in pysam.libcbcf.VariantFile.open
  File "pysam/libchtslib.pyx", line 518, in pysam.libchtslib.HTSFile.tell
NotImplementedError: seek not implemented in files compressed by method 1

Hope you can understand my description this time.
And what can I do for solving this?
Thanks,
tjiang

**Comment by ACEnglish** [comment]
I believe the problem is directly related to the following: https://github.com/pysam-developers/pysam/issues/536
Specifically the last comment which says, 
```Cheers! I realised my issue was actually due to the way the VCF file was compressed (needed to be bgzip)```
