### ISSUE TITLE
SVs without SVLEN in vcf file

### ISSUE THREAD

**Issue by tgong1** [spiralgenetics/truvari#4]
Hi,
I'd like to ask how truvari deal with SV entries without SVLEN, such as inter-chromosomal translocation, which does not have SVLEN in INFO in vcf file.

Thank you very much.

**Comment by ACEnglish** [comment]
There's a bit of logic in Truvari that tries a few ways to infer the size of the event. For entries without an SVLEN and without sequence resolved calls, we look for the END tag and subtract the start from that for the size. For sequence resolved calls it's simply the length of the ALT - the length of the REF. If that info isn't available (e.g. ALT = "<DEL>", no END), we use pyvcf's Record.end and Record.start. 
In general, Truvari is expecting vcfs to be very similar to GIAB's SVs VCF with sequence resolved calls and all the appropriate INFOs.
