### ISSUE TITLE
TypeError: '>=' not supported between instances of 'int' and 'NoneType'

### ISSUE THREAD

**Issue by shengbing** [spiralgenetics/truvari#40]
Detailed error messages:

Traceback (most recent call last):
  File "/dlmp/sandbox/cgslIS/DLMP_CGSL_OS/python3_env/bin/truvari", line 1047, in <module>
    run(sys.argv[1:])
  File "/dlmp/sandbox/cgslIS/DLMP_CGSL_OS/python3_env/bin/truvari", line 731, in run
    regions = GenomeTree(vcf_base, vcf_comp, args.includebed)
  File "/dlmp/sandbox/cgslIS/DLMP_CGSL_OS/python3_env/bin/truvari", line 537, in __init__
    all_regions[name].addi(0, length)
  File "/dlmp/sandbox/cgslIS/DLMP_CGSL_OS/python3_env/lib/python3.6/site-packages/intervaltree/intervaltree.py", line 343, in addi
    return self.add(Interval(begin, end, data))
  File "/dlmp/sandbox/cgslIS/DLMP_CGSL_OS/python3_env/lib/python3.6/site-packages/intervaltree/intervaltree.py", line 323, in add
    if interval.is_null():
  File "/dlmp/sandbox/cgslIS/DLMP_CGSL_OS/python3_env/lib/python3.6/site-packages/intervaltree/interval.py", line 116, in is_null
    return self.begin >= self.end
TypeError: '>=' not supported between instances of 'int' and 'NoneType'

Header and a few lines of the input:

##fileformat=VCFv4.2
##fileDate='Thu Dec 12 18:26:36 CST 2019'
##source=SentieonMGC-callerStr1-dynamic
##reference=HG19
##suppliedSex=MAL
##predictedSex=MALE
##avgRPKMCorrelationWrtTrainingSamples=0.937643587011545
##medianAbsoluteDeviation(log2R diff)=0.104296609837663
##log2RWaviness=1.4025688822472
##contig=<ID=chr1,Description=chromosome chr1>
##contig=<ID=chr2,Description=chromosome chr2>
##contig=<ID=chr3,Description=chromosome chr3>
##contig=<ID=chr4,Description=chromosome chr4>
##contig=<ID=chr5,Description=chromosome chr5>
##contig=<ID=chr6,Description=chromosome chr6>
##contig=<ID=chr7,Description=chromosome chr7>
##contig=<ID=chr8,Description=chromosome chr8>
##contig=<ID=chr9,Description=chromosome chr9>
##contig=<ID=chr10,Description=chromosome chr10>
##contig=<ID=chr11,Description=chromosome chr11>
##contig=<ID=chr12,Description=chromosome chr12>
##contig=<ID=chr13,Description=chromosome chr13>
##contig=<ID=chr14,Description=chromosome chr14>
##contig=<ID=chr15,Description=chromosome chr15>
##contig=<ID=chr16,Description=chromosome chr16>
##contig=<ID=chr17,Description=chromosome chr17>
##contig=<ID=chr18,Description=chromosome chr18>
##contig=<ID=chr19,Description=chromosome chr19>
##contig=<ID=chr20,Description=chromosome chr20>
##contig=<ID=chr21,Description=chromosome chr21>
##contig=<ID=chr22,Description=chromosome chr22>
##contig=<ID=chrX,Description=chromosome chrX>
##contig=<ID=chrY,Description=chromosome chrY>
##contig=<ID=chrM,Description=chromosome chrM>
##contig=<ID=chrGL000207.1,Description=chromosome chrGL000207.1>
##contig=<ID=chrGL000226.1,Description=chromosome chrGL000226.1>
##contig=<ID=chrGL000229.1,Description=chromosome chrGL000229.1>
##contig=<ID=chrGL000231.1,Description=chromosome chrGL000231.1>
##contig=<ID=chrGL000210.1,Description=chromosome chrGL000210.1>
##contig=<ID=chrGL000239.1,Description=chromosome chrGL000239.1>
##contig=<ID=chrGL000235.1,Description=chromosome chrGL000235.1>
##contig=<ID=chrGL000201.1,Description=chromosome chrGL000201.1>
##contig=<ID=chrGL000247.1,Description=chromosome chrGL000247.1>
##contig=<ID=chrGL000245.1,Description=chromosome chrGL000245.1>
##contig=<ID=chrGL000197.1,Description=chromosome chrGL000197.1>
##contig=<ID=chrGL000203.1,Description=chromosome chrGL000203.1>
##contig=<ID=chrGL000246.1,Description=chromosome chrGL000246.1>
##contig=<ID=chrGL000249.1,Description=chromosome chrGL000249.1>
##contig=<ID=chrGL000196.1,Description=chromosome chrGL000196.1>
##contig=<ID=chrGL000248.1,Description=chromosome chrGL000248.1>
##contig=<ID=chrGL000244.1,Description=chromosome chrGL000244.1>
##contig=<ID=chrGL000238.1,Description=chromosome chrGL000238.1>
##contig=<ID=chrGL000202.1,Description=chromosome chrGL000202.1>
##contig=<ID=chrGL000234.1,Description=chromosome chrGL000234.1>
##contig=<ID=chrGL000232.1,Description=chromosome chrGL000232.1>
##contig=<ID=chrGL000206.1,Description=chromosome chrGL000206.1>
##contig=<ID=chrGL000240.1,Description=chromosome chrGL000240.1>
##contig=<ID=chrGL000236.1,Description=chromosome chrGL000236.1>
##contig=<ID=chrGL000241.1,Description=chromosome chrGL000241.1>
##contig=<ID=chrGL000243.1,Description=chromosome chrGL000243.1>
##contig=<ID=chrGL000242.1,Description=chromosome chrGL000242.1>
##contig=<ID=chrGL000230.1,Description=chromosome chrGL000230.1>
##contig=<ID=chrGL000237.1,Description=chromosome chrGL000237.1>
##contig=<ID=chrGL000233.1,Description=chromosome chrGL000233.1>
##contig=<ID=chrGL000204.1,Description=chromosome chrGL000204.1>
##contig=<ID=chrGL000198.1,Description=chromosome chrGL000198.1>
##contig=<ID=chrGL000208.1,Description=chromosome chrGL000208.1>
##contig=<ID=chrGL000191.1,Description=chromosome chrGL000191.1>
##contig=<ID=chrGL000227.1,Description=chromosome chrGL000227.1>
##contig=<ID=chrGL000228.1,Description=chromosome chrGL000228.1>
##contig=<ID=chrGL000214.1,Description=chromosome chrGL000214.1>
##contig=<ID=chrGL000221.1,Description=chromosome chrGL000221.1>
##contig=<ID=chrGL000209.1,Description=chromosome chrGL000209.1>
##contig=<ID=chrGL000218.1,Description=chromosome chrGL000218.1>
##contig=<ID=chrGL000220.1,Description=chromosome chrGL000220.1>
##contig=<ID=chrGL000213.1,Description=chromosome chrGL000213.1>
##contig=<ID=chrGL000211.1,Description=chromosome chrGL000211.1>
##contig=<ID=chrGL000199.1,Description=chromosome chrGL000199.1>
##contig=<ID=chrGL000217.1,Description=chromosome chrGL000217.1>
##contig=<ID=chrGL000216.1,Description=chromosome chrGL000216.1>
##contig=<ID=chrGL000215.1,Description=chromosome chrGL000215.1>
##contig=<ID=chrGL000205.1,Description=chromosome chrGL000205.1>
##contig=<ID=chrGL000219.1,Description=chromosome chrGL000219.1>
##contig=<ID=chrGL000224.1,Description=chromosome chrGL000224.1>
##contig=<ID=chrGL000223.1,Description=chromosome chrGL000223.1>
##contig=<ID=chrGL000195.1,Description=chromosome chrGL000195.1>
##contig=<ID=chrGL000212.1,Description=chromosome chrGL000212.1>
##contig=<ID=chrGL000222.1,Description=chromosome chrGL000222.1>
##contig=<ID=chrGL000200.1,Description=chromosome chrGL000200.1>
##contig=<ID=chrGL000193.1,Description=chromosome chrGL000193.1>
##contig=<ID=chrGL000194.1,Description=chromosome chrGL000194.1>
##contig=<ID=chrGL000225.1,Description=chromosome chrGL000225.1>
##contig=<ID=chrGL000192.1,Description=chromosome chrGL000192.1>
##contig=<ID=chrNC_007605,Description=chromosome chrNC_007605>
##contig=<ID=chrhs37d5,Description=chromosome chrhs37d5>
##contig=<ID=phix,Description=chromosome phix>
##ALT=<ID=CNV,Description="Copy number variable region">
##ALT=<ID=DUP,Description="Duplication">
##ALT=<ID=DEL,Description="Deletion">
##INFO=<ID=SVTYPE,Number=1,Type=String,Description="Type of structural variant">
##INFO=<ID=END,Number=1,Type=Integer,Description="End position of the variant described in this
 record">
##INFO=<ID=SVLEN,Number=1,Type=Integer,Description="Difference in length between REF and ALT al
leles">
##INFO=<ID=SRC,Number=1,Type=String,Description="Source of this event">
##INFO=<ID=GENE,Number=1,Type=String,Description="Gene identifier",Source="reporting.bed">
##INFO=<ID=TRANSCRIPT,Number=1,Type=String,Description="Transcript identifier",Source="reportin
g.bed">
##INFO=<ID=LOC,Number=1,Type=String,Description="Feature identifier",Source="reporting.bed">
##INFO=<ID=PEERS,Number=1,Type=String,Description="Number of reference samples utilized for ana
lysis">
##INFO=<ID=IQR,Number=1,Type=Float,Description="Inter-quartile range of log2Ratio values among
training samples">
##INFO=<ID=FEATURE_CATEGORY,Number=.,Type=String,Description="Category to which feature belongs
 to">
##INFO=<ID=SNR,Number=1,Type=Float,Description="Signal-to-noise ratio for SNR">
##INFO=<ID=CALL,Number=1,Type=String,Description="Category call">
##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
##FORMAT=<ID=LG2R,Number=1,Type=Float,Description="CNV Log2 Ratio">
##FORMAT=<ID=ZSCORE,Number=1,Type=Float,Description="Z-Score">
##FORMAT=<ID=-LOG10PVALUE,Number=1,Type=Float,Description="-log10 transformed P-value">
##FORMAT=<ID=TRAINING,Number=1,Type=Integer,Description="Sample label (0:test, 1:training)">
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	HG002	NGS82-DV042	NGS82-DV008	NGS82-DV014	NGS82-DV043	NGS82-DV044	NGS82-DV051	HG003	HG004	NGS82-DV046	MGS82-DV047	NGS82-DV048	NGS82-DV049	NGS82-DV050	NGS82-DV001
chr1	1475628	.	G	<DEL>	.	.	SVTYPE=DEL;SNR=24.081;END=1475747;SVLEN
=120;GENE=476_458424_339453(TMEM240)_1.1_1;TRANSCRIPT=NA;LOC=0;SRC=SentieonMGC-callerStr1-dynam
ic;PEERS=14;IQR=0.135;FEATURE_CATEGORY=CAT1;CALL=DEL	GT:LG2R:ZSCORE:-LOG10PVALUE:TRAINING	1:0.505:-4.919:6.424:0	.:0.05:.:.:1	.:0.999:.:.:1	.:0.063:.:.:1	.:0.004:.:.:1	.:0.032
:.:.:1	.:0.018:.:.:1	.:0.083:.:.:1	.:0.348:.:.:1	.:0.023:.:.:1	.:0.101:.:.:1	.:0.089
:.:.:1	.:0.221:.:.:1	.:0.12:.:.:1	.:0.027:.:.:1

**Comment by ACEnglish** [comment]
See #39
