### ISSUE TITLE
[E::get_intv] Failed to parse TBX_GENERIC, was wrong -p [type] used?

### ISSUE THREAD

**Issue by shengbing** [spiralgenetics/truvari#41]
We are experiencing format issue of vcf entries. 

Header and one entry:

##fileformat=VCFv4.2
##fileDate=data
##source=SentieonMGC-callerStr1-dynamic
##reference=HG19
##suppliedSex=MAL
##predictedSex=MALE
##avgRPKMCorrelationWrtTrainingSamples=0.956284181786183
##medianAbsoluteDeviation(log2R diff)=0.113303658101527
##log2RWaviness=1.23294155429722
##contig=<ID=chr1,Description="chromosome chr1",length=249250621>
##contig=<ID=chr2,Description="chromosome chr2",length=243199373>
##contig=<ID=chr3,Description="chromosome chr3",length=198022430>
##contig=<ID=chr4,Description="chromosome chr4",length=191154276>
##contig=<ID=chr5,Description="chromosome chr5",length=180915260>
##contig=<ID=chr6,Description="chromosome chr6",length=171115067>
##contig=<ID=chr7,Description="chromosome chr7",length=159138663>
##contig=<ID=chr8,Description="chromosome chr8",length=146364022>
##contig=<ID=chr9,Description="chromosome chr9",length=141213431>
##contig=<ID=chr10,Description="chromosome chr10",length=135534747>
##contig=<ID=chr11,Description="chromosome chr11",length=135006516>
##contig=<ID=chr12,Description="chromosome chr12",length=133851895>
##contig=<ID=chr13,Description="chromosome chr13",length=115169878>
##contig=<ID=chr14,Description="chromosome chr14",length=107349540>
##contig=<ID=chr15,Description="chromosome chr15",length=102531392>
##contig=<ID=chr16,Description="chromosome chr16",length=90354753>
##contig=<ID=chr17,Description="chromosome chr17",length=81195210>
##contig=<ID=chr18,Description="chromosome chr18",length=78077248>
##contig=<ID=chr19,Description="chromosome chr19",length=59128983>
##contig=<ID=chr20,Description="chromosome chr20",length=63025520>
##contig=<ID=chr21,Description="chromosome chr21",length=48129895>
##contig=<ID=chr22,Description="chromosome chr22",length=51304566>
##contig=<ID=chrX,Description="chromosome chrX",length=155270560>
##contig=<ID=chrY,Description="chromosome chrY",length=59373566>
##contig=<ID=chrM,Description="chromosome chrM",length=16569>
##contig=<ID=chrGL000207.1,Description="chromosome chrGL000207.1",length=4262>
##contig=<ID=chrGL000226.1,Description="chromosome chrGL000226.1",length=15008>
##contig=<ID=chrGL000229.1,Description="chromosome chrGL000229.1",length=19913>
##contig=<ID=chrGL000231.1,Description="chromosome chrGL000231.1",length=27386>
##contig=<ID=chrGL000210.1,Description="chromosome chrGL000210.1",length=27682>
##contig=<ID=chrGL000239.1,Description="chromosome chrGL000239.1",length=33824>
##contig=<ID=chrGL000235.1,Description="chromosome chrGL000235.1",length=34474>
##contig=<ID=chrGL000201.1,Description="chromosome chrGL000201.1",length=36148>
##contig=<ID=chrGL000247.1,Description="chromosome chrGL000247.1",length=36422>
##contig=<ID=chrGL000245.1,Description="chromosome chrGL000245.1",length=36651>
##contig=<ID=chrGL000197.1,Description="chromosome chrGL000197.1",length=37175>
##contig=<ID=chrGL000203.1,Description="chromosome chrGL000203.1",length=37498>
##contig=<ID=chrGL000246.1,Description="chromosome chrGL000246.1",length=38154>
##contig=<ID=chrGL000249.1,Description="chromosome chrGL000249.1",length=38502>
##contig=<ID=chrGL000196.1,Description="chromosome chrGL000196.1",length=38914>
##contig=<ID=chrGL000248.1,Description="chromosome chrGL000248.1",length=39786>
##contig=<ID=chrGL000244.1,Description="chromosome chrGL000244.1",length=39929>
##contig=<ID=chrGL000238.1,Description="chromosome chrGL000238.1",length=39939>
##contig=<ID=chrGL000202.1,Description="chromosome chrGL000202.1",length=40103>
##contig=<ID=chrGL000234.1,Description="chromosome chrGL000234.1",length=40531>
##contig=<ID=chrGL000232.1,Description="chromosome chrGL000232.1",length=40652>
##contig=<ID=chrGL000206.1,Description="chromosome chrGL000206.1",length=41001>
##contig=<ID=chrGL000240.1,Description="chromosome chrGL000240.1",length=41933>
##contig=<ID=chrGL000236.1,Description="chromosome chrGL000236.1",length=41934>
##contig=<ID=chrGL000241.1,Description="chromosome chrGL000241.1",length=42152>
##contig=<ID=chrGL000243.1,Description="chromosome chrGL000243.1",length=43341>
##contig=<ID=chrGL000242.1,Description="chromosome chrGL000242.1",length=43523>
##contig=<ID=chrGL000230.1,Description="chromosome chrGL000230.1",length=43691>
##contig=<ID=chrGL000237.1,Description="chromosome chrGL000237.1",length=45867>
##contig=<ID=chrGL000233.1,Description="chromosome chrGL000233.1",length=45941>
##contig=<ID=chrGL000204.1,Description="chromosome chrGL000204.1",length=81310>
##contig=<ID=chrGL000198.1,Description="chromosome chrGL000198.1",length=90085>
##contig=<ID=chrGL000208.1,Description="chromosome chrGL000208.1",length=92689>
##contig=<ID=chrGL000191.1,Description="chromosome chrGL000191.1",length=106433>
##contig=<ID=chrGL000227.1,Description="chromosome chrGL000227.1",length=128374>
##contig=<ID=chrGL000228.1,Description="chromosome chrGL000228.1",length=129120>
##contig=<ID=chrGL000214.1,Description="chromosome chrGL000214.1",length=137718>
##contig=<ID=chrGL000221.1,Description="chromosome chrGL000221.1",length=155397>
##contig=<ID=chrGL000209.1,Description="chromosome chrGL000209.1",length=159169>
##contig=<ID=chrGL000218.1,Description="chromosome chrGL000218.1",length=161147>
##contig=<ID=chrGL000220.1,Description="chromosome chrGL000220.1",length=161802>
##contig=<ID=chrGL000213.1,Description="chromosome chrGL000213.1",length=164239>
##contig=<ID=chrGL000211.1,Description="chromosome chrGL000211.1",length=166566>
##contig=<ID=chrGL000199.1,Description="chromosome chrGL000199.1",length=169874>
##contig=<ID=chrGL000217.1,Description="chromosome chrGL000217.1",length=172149>
##contig=<ID=chrGL000216.1,Description="chromosome chrGL000216.1",length=172294>
##contig=<ID=chrGL000215.1,Description="chromosome chrGL000215.1",length=172545>
##contig=<ID=chrGL000205.1,Description="chromosome chrGL000205.1",length=174588>
##contig=<ID=chrGL000219.1,Description="chromosome chrGL000219.1",length=179198>
##contig=<ID=chrGL000224.1,Description="chromosome chrGL000224.1",length=179693>
##contig=<ID=chrGL000223.1,Description="chromosome chrGL000223.1",length=180455>
##contig=<ID=chrGL000195.1,Description="chromosome chrGL000195.1",length=182896>
##contig=<ID=chrGL000212.1,Description="chromosome chrGL000212.1",length=186858>
##contig=<ID=chrGL000222.1,Description="chromosome chrGL000222.1",length=186861>
##contig=<ID=chrGL000200.1,Description="chromosome chrGL000200.1",length=187035>
##contig=<ID=chrGL000193.1,Description="chromosome chrGL000193.1",length=189789>
##contig=<ID=chrGL000194.1,Description="chromosome chrGL000194.1",length=191469>
##contig=<ID=chrGL000225.1,Description="chromosome chrGL000225.1",length=211173>
##contig=<ID=chrGL000192.1,Description="chromosome chrGL000192.1",length=547496>
##contig=<ID=chrNC_007605,Description="chromosome chrNC_007605",length=171823>
##contig=<ID=chrhs37d5,Description="chromosome chrhs37d5",length=35477943>
##contig=<ID=phix,Description="chromosome phix",length=5386>
##ALT=<ID=CNV,Description="Copy number variable region">
##ALT=<ID=DEL,Description="Deletion">
##ALT=<ID=DUP,Description="Duplication">
##INFO=<ID=SVTYPE,Number=1,Type=String,Description="Type of structural variant">
##INFO=<ID=END,Number=1,Type=Integer,Description="End position of the variant described in this record">
##INFO=<ID=SVLEN,Number=1,Type=Integer,Description="Difference in length between REF and ALT alleles">
##INFO=<ID=SRC,Number=1,Type=String,Description="Source of this event">
##INFO=<ID=GENE,Number=1,Type=String,Description="Gene identifier",Source="reporting.bed">
##INFO=<ID=TRANSCRIPT,Number=1,Type=String,Description="Transcript identifier",Source="reporting.bed">
##INFO=<ID=LOC,Number=1,Type=String,Description="Feature identifier",Source="reporting.bed">
##INFO=<ID=PEERS,Number=1,Type=String,Description="Number of reference samples utilized for analysis">
##INFO=<ID=IQR,Number=1,Type=Float,Description="Inter-quartile range of log2Ratio values among training samples">
##INFO=<ID=FEATURE_CATEGORY,Number=.,Type=String,Description="Category to which feature belongs to">
##INFO=<ID=SNR,Number=1,Type=Float,Description="Signal-to-noise ratio for SNR">
##INFO=<ID=CALL,Number=1,Type=String,Description="Category call">
##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
##FORMAT=<ID=LG2R,Number=1,Type=Float,Description="CNV Log2 Ratio">
##FORMAT=<ID=ZSCORE,Number=1,Type=Float,Description="Z-Score">
##FORMAT=<ID=MINUSLOG10PVALUE,Number=1,Type=Float,Description="-log10 transformed P-value">
##FORMAT=<ID=TRAINING,Number=1,Type=Integer,Description="Sample label (0:test, 1:training)">
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	NGS82-DV001	HG002NGS82-DV008	VIP4-DAUGHTER	NGS82-DV024	NGS82-DV041	NGS82-DV033	2019-NORM-CTRLNGS82-DV002	NGS82-DV036	NGS82-DV009	NGS82-DV012	DONOR5-WBH-P	DONOR6-WBA-C	DONOR7-WBA-P	VIP3-FATHER
chr2	130951460	.	T	<DUP>	.	.	SVTYPE=DUP;SNR=24.857;END=130951579;SVLEN=120;GENE=TUBA3E;TRANSCRIPT=NM_207312.2;LOC=Ex4;SRC=SentieonMGC-callerStr1-dynamic;PEERS=15;IQR=0.213;FEATURE_CATEGORY=CAT1;CALL=DUP	GT:LG2R:ZSCORE:MINUSLOG10PVALUE:TRAINING	1:0.579:6.888:11.247:0	.:0.005:.:.:1	.:0.006:.:.:1	.:0.006:.:.:1	.:0.002:.:.:1.:0.045:.:.:1	.:0.002:.:.:1	.:0.108:.:.:1	.:0.444:.:.:1	.:0.058:.:.:1	.:0.322:.:.:1.:0.656:.:.:1	.:0.07:.:.:1	.:0.003:.:.:1	.:0.409:.:.:1	.:0.092:.:.:1

Error message:

The offending line was: "chr9	2622171	.	G	<DEL>	.	.	SVTYPE=DEL;SNR=24.979;END=2622290;SVLEN=120;GENE=VLDLR;TRANSCRIPT=NM_003383.4;LOC=5UTR;SRC=SentieonMGC-callerStr1-dynamic;PEERS=15;IQR=0.134;FEATURE_CATEGORY=CAT1;CALL=DEL	GT:LG2R:ZSCORE:MINUSLOG10PVALUE:TRAINING	1:0.767:-8.375:21.2:0	.:0.059:.:.:1	.:0.093:.:.:1	.:0.045:.:.:1	.:0.119:.:.:1	.:0.023:.:.:1	.:0.081:.:.:1	.:0.005:.:.:1	.:0.049:.:.:1	.:0.092:.:.:1	.:0.005:.:.:1	.:0.102:.:.:1	.:0.099:.:.:1	.:0.009:.:.:1	.:0.104:.:.:1	.:0.023:.:.:1"
[E::get_intv] Failed to parse TBX_GENERIC, was wrong -p [type] used?
The offending line was: "chrX	71822006	.	T	<DUP>	.	.	SVTYPE=DUP;SNR=22.545;END=71822125;SVLEN=120;GENE=PHKA1;TRANSCRIPT=NM_002637.3;LOC=In27/28;SRC=SentieonMGC-callerStr1-dynamic;PEERS=15;IQR=0.177;FEATURE_CATEGORY=CAT1;CALL=DUP	GT:LG2R:ZSCORE:MINUSLOG10PVALUE:TRAINING	1:0.6:3.554:3.421:0	.:0.152:.:.:1	.:0.142:.:.:1	.:0.167:.:.:1	.:0.056:.:.:1	.:0.07:.:.:1	.:0.043:.:.:1	.:0.053:.:.:1	.:0.251:.:.:1	.:0.113:.:.:1	.:0.043:.:.:1	.:0.584:.:.:1	.:0.283:.:.:1	.:0.116:.:.:1	.:0.051:.:.:1	.:0.053:.:.:1"
 [Elapsed Time: 0:00:00 129/129] |########################################| (Time:  0:00:00)
2019-12-17 09:48:04,795 [WARNING] No TP or FP calls in base!
2019-12-17 09:48:04,795 [INFO] Parsing FPs from calls
 [Elapsed Time: 0:00:00 129/129] |########################################| (Time:  0:00:00)

**Comment by ACEnglish** [comment]
I would guess that there is a problem with this file's tabix index. 
Please try to regenerate the index with 
``` tabix comparison.vcf.gz```

**Comment by shengbing** [comment]
Thanks. You are right.
