### ISSUE TITLE
What does 'sequence resolved calls' mean?

### ISSUE THREAD

**Issue by gorupria** [spiralgenetics/truvari#42]
Dear Truvari developers,

In truvari document, the term 'sequence resolved calls' has been mentioned. I quite did not get the meaning. Would you please explain it.

**Comment by ACEnglish** [comment]
Hi,
 Sequence resolved means that the full allele's sequence is present in the vcf along with the exact coordinates of the SVs change of the reference.
For example, a sequence resolved insertion would look something like
```
#CHROM POS ID REF ALT...INFO
1 1234 . A ATCGATCGATCG ... END=12345;SVTYPE=INS
```
A non-sequence resolved call generally has 'fuzzy' boundaries and an estimation of the event size. 
```
#CHROM POS ID REF ALT...INFO
1 1230 . A <INS>..END=1240;CISTART=-5,5;CIEND=-6'6;SVLEN=10
```
Where CI is the confidence interval around the start/end where the breakpoint is likely to exist.
