### ISSUE TITLE
Does SVTYPE of a variant must be either DEL or INS for Truvari to be able to handle it? 

### ISSUE THREAD

**Issue by gorupria** [spiralgenetics/truvari#44]
Dear Truvari developers,

Is it so that Truvari needs to have 'DEL' or 'INS' as SVTYPE, meaning it would not be able to benchmark variants with SVTYPE=DUP for instance? For example, I have this variant

19	8998800	DUP_delly_421	N	<DUP>	1000	PASS	SVTYPE=DUP;SVMETHOD=EMBL.DELLYv0.7.8;CHR2=19;END=9010766;SVLEN=11966;OCC=1;FRQ=0.000447427	GT	0/0

Truvari does not return this as true positive if SVTYPE is 'DUP'

However if I change 'DUP' to 'INS', 

19	8998800	DUP_delly_421	N	<DUP>	1000	PASS	SVTYPE=INS;SVMETHOD=EMBL.DELLYv0.7.8;CHR2=19;END=9010766;SVLEN=11966;OCC=1;FRQ=0.000447427	GT	0/0

it seems to return it as true positive. 

Also, in many other samples, Truvari seems to catch DEL ones better than INS. It did not for once returned DUP ones as true positive.

**Comment by ACEnglish** [comment]
Hello,

Truvari pulls the type of a variant with the following procedure:
```
    """
    How svtype is determined:
    - Starts by trying to use INFO/SVTYPE
    - If SVTYPE is unavailable, infer if entry is a insertion or deletion by
      looking at the REF/ALT sequence size differences
    - If REF/ALT sequences are not available, try to parse the <INS>, <DEL>,
      etc from the ALT column.
    - Otherwise, assume 'UNK'
    """
```
The SVTYPE returned must match between the base and comparison calls. We have built no kind of synonyms to be inferred between different classifications. This could quickly become quite complex and is without a standard (e.g. There's nothing stopping someone wanting their TANDEM:DEL to match with DEL, or your case of INS with DUP). Therefore the SVTYPEs must be exact matches. For your case, you'd either want to reannotate your base SVs so they're of the expected 'DUP' type or continue to change your comparison INS to DUPs.
