### ISSUE TITLE
Truvari not adding variants to call count or interval tree for comparsion.

### ISSUE THREAD

**Issue by gorupria** [spiralgenetics/truvari#45]
Dear Truvari developer,

I have this variant,
1	108734987	.	T	<DEL>	20	PASS	SVTYPE=DEL;SVLEN=-379;END=108735366	GT:GTcons1:PB_GT:PB_REF:PB_ALT:PBHP_GT:PB_REF_HP1:PB_ALT_HP1:PB_REF_HP2:PB_ALT_HP2:TenX_GT:TenX_REF_HP1:TenX_ALT_HP1:TenX_REF_HP2:TenX_ALT_HP2:ILL250bp_GT:ILL250bp_REF:ILL250bp_ALT:ILLMP_GT:ILLMP_REF:ILLMP_ALT:BNG_LEN_DEL:BNG_LEN_INS:nabsys_svm	1/1:1/1:1/1:2:110:./.:0:2:0:2:./.:1:12:0:10:1/1:0:30:1/1:3:285:5046:.:.

I am using --includebed parameter of truvari and this variant is covered by this region in my bed file
1	108734987	108735366

This variant is being discarded by truvari and is not added to a call count. However, when I extended the bed region by 1 (Note that bed region is exactly same as start and end of this variant) like this
1	108734986	108735367
truvari adds it to the call count and performs the comparison. Is it intended to behave like this? or could it be by any chance 'Off by 1' bug?

**Comment by ACEnglish** [comment]
Yes, this is an off-by-1.  Bed file positions are 0-based half-open intervals, where VCF file positions are 1-based. So for your example, if we translate the VCF's position to the bed's position, it starts at  `108734986`. Therefore, once you change your bed to the second reported interval, you correctly see the call being counted.
  Truvari had a feature request early on that we only include VCF entries with starts AND ends contained within a single includebed interval.
