### ISSUE TITLE
setup.py exact dependency versions

### ISSUE THREAD

**Issue by KoviRobi** [spiralgenetics/truvari#46]
Hi,

I was just wondering, is there any reason for the `setup.py` to have
```
        "python-Levenshtein==0.12.0",
        "progressbar2==3.41.0",
        "pysam==0.15.2",
        "pyfaidx==0.5.5.2",
        "intervaltree==3.0.2",
```
and not
```
        "python-Levenshtein>=0.12.0",
        "progressbar2>=3.41.0",
        "pysam>=0.15.2",
        "pyfaidx>=0.5.5.2",
        "intervaltree>=3.0.2",
```

I just came across this package because it's broken in the nixpkgs repo, because we are using `pyfaidx` version 0.5.8.

Thanks for any clarification,
Robert

**Comment by ACEnglish** [comment]
Hello,

I did a cursory check and I'm pretty sure it'll be okay to switch to `>=` for these packages. I've checked in the change to 076c235 , but I won't cut a new release (1.3.5) until I've done more checks and consolidated some larger changes from a feature branch I've been working on. If you'd like to use these changes now, you can run the following commands:

```bash
git checkout https://github.com/spiralgenetics/truvari.git
cd truvari
python setup.py sdist bdist_wheel
pip install dist/Truvari-1.3.4.tar.gz
```
Have a great day,
~/Adam English
