### ISSUE TITLE
Potential typo in get_vcf_variant_type()

### ISSUE THREAD

**Issue by eldariont** [spiralgenetics/truvari#47]
Hi,

when comparing VCF files that use symbolic alleles (e.g. \<DEL>) without setting the INFO/SVTYPE, truvari version 1.3.4 fails because the variable name `mat` is unknown in get_vcf_variant_type(entry).

I think there is a typo in https://github.com/spiralgenetics/truvari/blob/develop/truvari/truvari#L208 and `mat` should be `mat1`.

Cheers
David

**Comment by ACEnglish** [comment]
Fixed. Thank you!
