### ISSUE TITLE
SVs that partially overlap bed file

### ISSUE THREAD

**Issue by jzook** [spiralgenetics/truvari#5]
It looks like truvari might currently include variants in the TP, FP, and FN counts if they only partially overlap the include bed file.  I think these should probably be excluded, since now large deletions in the query set often appear to be FPs when in fact they might be mostly outside the high-confidence bed.

**Comment by ACEnglish** [comment]
This was a very easy fix... at first.
I'm now simply checking if a variant's start AND end pass the PyIntervalTree's `overlap` search.

However, I realized there's an edge case where an event could start in one includebed region and end in another i.e. it the variant spans a non-highconfidence region.
I believe the behavior should be that this event should stay included as a FP, but wanted to see if you thought differently before I closed this ticket.

**Comment by jzook** [comment]
Thanks! I think we probably want to exclude variants that span a non-high-confidence region even if they start and end in high confidence regions.  I think otherwise we could end up calling large deletions as FPs if they are correct but imprecisely defined.

**Comment by ACEnglish** [comment]
Finished. You can use this feature in develop. i'll hold off on tagging a  new release until I finish #8 and possibly #7 as well.
