### ISSUE TITLE
Error: values expected to be 2-tuple, given len=1

### ISSUE THREAD

**Issue by cjain7** [spiralgenetics/truvari#54]
Hi, I am trying to process sniffles vcf output using truvari (v1.3.4) and GIAB v0.6 SV benchmark. I'm following the same recipe to post-process sniffles output as described here 
https://github.com/PacificBiosciences/sv-benchmark

However, I'm getting an error (complete debug log attached). Can you please suggest a fix to this issue?

Thanks!
[truvari_debug_log.txt](https://github.com/spiralgenetics/truvari/files/4860254/truvari_debug_log.txt)
[output_s5.vcf.gz](https://github.com/spiralgenetics/truvari/files/4860270/output_s5.vcf.gz)

**Comment by ACEnglish** [comment]
It appears you have an error in the vcf file. I wrote a rough tool to check vcfs [usable_vcf](https://github.com/acenglish/usable_vcf). Running it over your `output_s5.vcf.gz` shows the attached errors. To start, your `REF_strand` INFO field is defined as having `Number=2`, but each occurrence appears to only have a single item. See the [vcf specification](https://samtools.github.io/hts-specs/VCFv4.3.pdf) for details. There are other errors I'll leave to you to resolve.

[vcfcheck.log.gz](https://github.com/spiralgenetics/truvari/files/4866749/vcfcheck.log.gz)
