### ISSUE TITLE
‘Mismatch when double-checking Truvari calculations

### ISSUE THREAD

**Issue by shengbing** [spiralgenetics/truvari#56]
Dear Truvari development team,

 
We recently used Truvari for a project comparing SV detection performance but the performance metrics did not match with our scripts. Here's the command used to run Truvari (input files attached):
 
/usr/local/biotools/python/3.6.3/bin/truvari -b ref.vcf.gz -c test.vcf.gz -o ${OUTDIR} --includebed include.bed --pctsim 0
 
Output:
     "TP-base": 6405,
    "TP-call": 6405,
    "FP": 160,
    "FN": 367,
    "precision": 0.9756283320639756,
    "recall": 0.9458062610750148,
    "base cnt": 6772,
    "call cnt": 6565,
    "base size filtered": 0,
    "call size filtered": 0,
    "base gt filtered": 0,
    "call gt filtered": 0,
    "TP-call_TP-gt": 6405,
    "TP-call_FP-gt": 0,
    "TP-base_TP-gt": 6405,
    "TP-base_FP-gt": 0,
    "gt_precision": 0.9756283320639756,
    "gt_recall": 0.9458062610750148,
 
Output from our scripts (r.cmd.txt: code attached):
 
Note: In the R code, run.all.melt is essentially test.vcf in tabular form with different column names.
 
#dups.perf.df
sample dup.TP dup.FP dup.TN dup.FN dups.SENS dups.SPEC  dups.PPV dups.NPV     dups.FPR   dups.FDR
2019-NORMCTRL-i  12350    240 397794   1775 0.8743363  0.999397 0.9809373 1 0.9955577 0.0006029636 0.01906275

#dels.perf.df
sample del.TP del.FP del.TN del.FN dels.SENS dels.SPEC   dels.PPV dels.NPV     dels.FPR  dels.FDR
2019-NORMCTRL-i      9    156 411992      2 0.8181818 0.9996215 0.05454545 0.9999951 0.0003785048 0.9454545
 
All the input files and our code are attached. Please let me know if you require more info.

Best,

Shengbing Huang, Ph.D, MS
Assistant Professor of Medicine
IT Analyst/Programmer

[Archive.zip](https://github.com/spiralgenetics/truvari/files/5256591/Archive.zip)

**Comment by ACEnglish** [comment]
It appears that the `[findOverlaps](http://web.mit.edu/~r/current/arch/i386_linux26/lib/R/library/GenomicRanges/html/findOverlaps-methods.html)`, particularly when run as demonstrated in your example code, has different behavior from Truvari. See [the wiki](https://github.com/spiralgenetics/truvari/wiki/bench) for details on the truvari methodology.

**Comment by shengbing** [comment]
Hi Adam,
 
Can you kindly provide us suggestions with respect to Truvari parameters such that we will have same behavior as our code? Great thanks to your assistance!
 
Best,
 
Shengbing
