### ISSUE TITLE
Truvari does not recognize call in base VCF

### ISSUE THREAD

**Issue by botcricket** [spiralgenetics/truvari#57]
**Command** 
/usr/local/biotools/python/3.6.3/bin/truvari -b ${GOLD_VCF}.gz -c ${COMP_VCF}.gz -o ${OUTDIR} --pctsim 0

**Issue**
When I try and run the following VCF, Truvari prints out the warning, 'No TP or FN calls in base!' and as a result shows 0 for both the precision and recall metrics. Why can't it recognize the variant? I tried looking for and deleting weird characters, but that does not seem to be the issue. Please help 

**Input: GOLD_VCF**
##fileformat=VCFv4.2
##contig=<ID=chr1,Description="chromosome chr1",length=249250621>
##contig=<ID=chr2,Description="chromosome chr2",length=243199373>
##contig=<ID=chr3,Description="chromosome chr3",length=198022430>
##contig=<ID=chr4,Description="chromosome chr4",length=191154276>
##contig=<ID=chr5,Description="chromosome chr5",length=180915260>
##contig=<ID=chr6,Description="chromosome chr6",length=171115067>
##contig=<ID=chr7,Description="chromosome chr7",length=159138663>
##contig=<ID=chr8,Description="chromosome chr8",length=146364022>
##contig=<ID=chr9,Description="chromosome chr9",length=141213431>
##contig=<ID=chr10,Description="chromosome chr10",length=135534747>
##contig=<ID=chr11,Description="chromosome chr11",length=135006516>
##contig=<ID=chr12,Description="chromosome chr12",length=133851895>
##contig=<ID=chr13,Description="chromosome chr13",length=115169878>
##contig=<ID=chr14,Description="chromosome chr14",length=107349540>
##contig=<ID=chr15,Description="chromosome chr15",length=102531392>
##contig=<ID=chr16,Description="chromosome chr16",length=90354753>
##contig=<ID=chr17,Description="chromosome chr17",length=81195210>
##contig=<ID=chr18,Description="chromosome chr18",length=78077248>
##contig=<ID=chr19,Description="chromosome chr19",length=59128983>
##contig=<ID=chr20,Description="chromosome chr20",length=63025520>
##contig=<ID=chr21,Description="chromosome chr21",length=48129895>
##contig=<ID=chr22,Description="chromosome chr22",length=51304566>
##contig=<ID=chrX,Description="chromosome chrX",length=155270560>
##contig=<ID=chrY,Description="chromosome chrY",length=59373566>
##contig=<ID=chrM,Description="chromosome chrM",length=16569>
##contig=<ID=chrGL000207.1,Description="chromosome chrGL000207.1",length=4262>
##contig=<ID=chrGL000226.1,Description="chromosome chrGL000226.1",length=15008>
##contig=<ID=chrGL000229.1,Description="chromosome chrGL000229.1",length=19913>
##contig=<ID=chrGL000231.1,Description="chromosome chrGL000231.1",length=27386>
##contig=<ID=chrGL000210.1,Description="chromosome chrGL000210.1",length=27682>
##contig=<ID=chrGL000239.1,Description="chromosome chrGL000239.1",length=33824>
##contig=<ID=chrGL000235.1,Description="chromosome chrGL000235.1",length=34474>
##contig=<ID=chrGL000201.1,Description="chromosome chrGL000201.1",length=36148>
##contig=<ID=chrGL000247.1,Description="chromosome chrGL000247.1",length=36422>
##contig=<ID=chrGL000245.1,Description="chromosome chrGL000245.1",length=36651>
##contig=<ID=chrGL000197.1,Description="chromosome chrGL000197.1",length=37175>
##contig=<ID=chrGL000203.1,Description="chromosome chrGL000203.1",length=37498>
##contig=<ID=chrGL000246.1,Description="chromosome chrGL000246.1",length=38154>
##contig=<ID=chrGL000249.1,Description="chromosome chrGL000249.1",length=38502>
##contig=<ID=chrGL000196.1,Description="chromosome chrGL000196.1",length=38914>
##contig=<ID=chrGL000248.1,Description="chromosome chrGL000248.1",length=39786>
##contig=<ID=chrGL000244.1,Description="chromosome chrGL000244.1",length=39929>
##contig=<ID=chrGL000238.1,Description="chromosome chrGL000238.1",length=39939>
##contig=<ID=chrGL000202.1,Description="chromosome chrGL000202.1",length=40103>
##contig=<ID=chrGL000234.1,Description="chromosome chrGL000234.1",length=40531>
##contig=<ID=chrGL000232.1,Description="chromosome chrGL000232.1",length=40652>
##contig=<ID=chrGL000206.1,Description="chromosome chrGL000206.1",length=41001>
##contig=<ID=chrGL000240.1,Description="chromosome chrGL000240.1",length=41933>
##contig=<ID=chrGL000236.1,Description="chromosome chrGL000236.1",length=41934>
##contig=<ID=chrGL000241.1,Description="chromosome chrGL000241.1",length=42152>
##contig=<ID=chrGL000243.1,Description="chromosome chrGL000243.1",length=43341>
##contig=<ID=chrGL000242.1,Description="chromosome chrGL000242.1",length=43523>
##contig=<ID=chrGL000230.1,Description="chromosome chrGL000230.1",length=43691>
##contig=<ID=chrGL000237.1,Description="chromosome chrGL000237.1",length=45867>
##contig=<ID=chrGL000233.1,Description="chromosome chrGL000233.1",length=45941>
##contig=<ID=chrGL000204.1,Description="chromosome chrGL000204.1",length=81310>
##contig=<ID=chrGL000198.1,Description="chromosome chrGL000198.1",length=90085>
##contig=<ID=chrGL000208.1,Description="chromosome chrGL000208.1",length=92689>
##contig=<ID=chrGL000191.1,Description="chromosome chrGL000191.1",length=106433>
##contig=<ID=chrGL000227.1,Description="chromosome chrGL000227.1",length=128374>
##contig=<ID=chrGL000228.1,Description="chromosome chrGL000228.1",length=129120>
##contig=<ID=chrGL000214.1,Description="chromosome chrGL000214.1",length=137718>
##contig=<ID=chrGL000221.1,Description="chromosome chrGL000221.1",length=155397>
##contig=<ID=chrGL000209.1,Description="chromosome chrGL000209.1",length=159169>
##contig=<ID=chrGL000218.1,Description="chromosome chrGL000218.1",length=161147>
##contig=<ID=chrGL000220.1,Description="chromosome chrGL000220.1",length=161802>
##contig=<ID=chrGL000213.1,Description="chromosome chrGL000213.1",length=164239>
##contig=<ID=chrGL000211.1,Description="chromosome chrGL000211.1",length=166566>
##contig=<ID=chrGL000199.1,Description="chromosome chrGL000199.1",length=169874>
##contig=<ID=chrGL000217.1,Description="chromosome chrGL000217.1",length=172149>
##contig=<ID=chrGL000216.1,Description="chromosome chrGL000216.1",length=172294>
##contig=<ID=chrGL000215.1,Description="chromosome chrGL000215.1",length=172545>
##contig=<ID=chrGL000205.1,Description="chromosome chrGL000205.1",length=174588>
##contig=<ID=chrGL000219.1,Description="chromosome chrGL000219.1",length=179198>
##contig=<ID=chrGL000224.1,Description="chromosome chrGL000224.1",length=179693>
##contig=<ID=chrGL000223.1,Description="chromosome chrGL000223.1",length=180455>
##contig=<ID=chrGL000195.1,Description="chromosome chrGL000195.1",length=182896>
##contig=<ID=chrGL000212.1,Description="chromosome chrGL000212.1",length=186858>
##contig=<ID=chrGL000222.1,Description="chromosome chrGL000222.1",length=186861>
##contig=<ID=chrGL000200.1,Description="chromosome chrGL000200.1",length=187035>
##contig=<ID=chrGL000193.1,Description="chromosome chrGL000193.1",length=189789>
##contig=<ID=chrGL000194.1,Description="chromosome chrGL000194.1",length=191469>
##contig=<ID=chrGL000225.1,Description="chromosome chrGL000225.1",length=211173>
##contig=<ID=chrGL000192.1,Description="chromosome chrGL000192.1",length=547496>
##contig=<ID=chrNC_007605,Description="chromosome chrNC_007605",length=171823>
##contig=<ID=chrhs37d5,Description="chromosome chrhs37d5",length=35477943>
##contig=<ID=phix,Description="chromosome phix",length=5386>
##ALT=<ID=CNV,Description="Copy number variable region">
##ALT=<ID=DEL,Description="Deletion">
##ALT=<ID=DUP,Description="Duplication">
##INFO=<ID=SVTYPE,Number=1,Type=String,Description="Type of structural variant">
##INFO=<ID=END,Number=1,Type=Integer,Description="End position of the variant described in this record">
##INFO=<ID=SVLEN,Number=1,Type=Integer,Description="Difference in length between REF and ALT alleles">
##INFO=<ID=SRC,Number=1,Type=String,Description="Source of this event">
##INFO=<ID=GENE,Number=1,Type=String,Description="Gene identifier",Source="reporting.bed">
##INFO=<ID=TRANSCRIPT,Number=1,Type=String,Description="Transcript identifier",Source="reporting.bed">
##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
##FORMAT=<ID=LG2R,Number=1,Type=Float,Description="CNV Log2 Ratio">
##FORMAT=<ID=ZSCORE,Number=1,Type=Float,Description="Z-Score">
##FORMAT=<ID=MINUSLOG10PVALUE,Number=1,Type=Float,Description="-log10 transformed P-value">
##FORMAT=<ID=RPKM,Number=1,Type=Float,Description="Reads Per Kilobase of transcript per Million mapped reads">
##FORMAT=<ID=AVGBPCOVG,Number=1,Type=Float,Description="Average base-pair coverage">
##FORMAT=<ID=TRAINING,Number=1,Type=Integer,Description="Sample label (0:test, 1:training)">
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	2019-NORMCTRL-i
chr8	10692171	.	A	<DUP>	.	.	SVTYPE=.;END=10692290;SVLEN=120;GENE=ABCA1;TRANSCRIPT=ENST00000435915.1	GT	0/1

**Comment by ACEnglish** [comment]
Given the paste of `Input: GOLD_VCF`, I ran it through [vcf-validator](https://vcftools.github.io/perl_module.html#vcf-validator)

```
Wrong number of fieldsin broken.vcf.gz; expected 10, got 9. The offending line was:
[chr8	10692171	.	A	.	.	SVTYPE=.;END=10692290;SVLEN=120;GENE=ABCA1;TRANSCRIPT=ENST00000435915.1	GT	0/1]
```
