### ISSUE TITLE
simple fix to README

### ISSUE THREAD

**Issue by RichardCorbett** [spiralgenetics/truvari#63]
Hi folks,

In your READE it gives this example:
`truvari bench -b base.vcf.gz -c comp.vcf.gz -r reference.fasta -o output_dir/`

From what I can tell as I try to get this running it should actually be:
`truvari bench -b base.vcf.gz -c comp.vcf.gz -f reference.fasta -o output_dir/`

**Comment by ACEnglish** [comment]
Thanks for spotting this. Readme has been updated.
