### ISSUE TITLE
can truvari evaluate vcfs on haplotype level

### ISSUE THREAD

**Issue by yekaizhou** [spiralgenetics/truvari#66]
Say, given two vcf files with phasing information, can truvari benchmark precision/F1 on each haplotype level?

**Comment by ACEnglish** [comment]
Unfortunately, no. The phase information is not taken into consideration. Your best bet would be manually separating the haplotypes, creating two pairs of VCFs and running Truvari on each. You can use pysam to help you script the separation. Below is pseudocode I'm mocking up on the fly that might be able to get you started:
```python
import pysam

input_vcf = pysam.VariantFile("combined.haplotypes.vcf.gz")
hap1 = pysam.VariantFile("hap1.vcf.gz", 'w', header=input_vcf.header)
hap2 = pysam.VariantFile("hap1.vcf.gz", 'w', header=input_vcf.header)

for entry in input_vcf:
    if entry.samples[0]["GT"] == (1, 1): # Hom
        hap1.write(entry)
        hap2.write(entry)
    elif entry.samples[0]["GT"] == (1, 0): # Het hap1
        hap1.write(entry)
    elif entry.samples[0]["GT"] == (0, 1): # Het hap2
        hap2.write(entry)
    else:
        print("Bad genotype on ", str(entry))
```
