### ISSUE TITLE
truset file as bed

### ISSUE THREAD

**Issue by Manuelaio** [spiralgenetics/truvari#68]
Dear, 
I'm writing to have information about the truset file in truvari benchmark analysis. I have a bed file with "true" SVs variants of NA12878 (without genotype columns) that I would to use as my true set, I converted it in a vcf file but I obtain the following error 
`sampleA = vcf_base.samples[0]
IndexError: list index out of range
`
I'd really appreciate to know the required columns to use the benchmark option in order to prepare my bed file or if there is a specific option to solve this problem. Many thanks

**Comment by ACEnglish** [comment]
Hello,

We've documented common challenges with using VCFs on the [wiki](https://github.com/spiralgenetics/truvari/wiki) with a [link to a tool ](https://github.com/acenglish/usable_vcf) that can help you validate your files. To answer your question directly, each of the standard [VCF columns ](https://samtools.github.io/hts-specs/VCFv4.2.pdf) need to be present.

Have a great day,
~/Adam
