### ISSUE TITLE
problem for using truvari

### ISSUE THREAD

**Issue by azure-twilight** [spiralgenetics/truvari#71]
I use SURVIVOR to simulate SVs and get sv.vcf, then use svim to detect sv and get all.vcf
I want to use truvari to compare sv.vcf and all.vcf.
First I use bgzip to get .gz file and use tabix -p vcf  xx.vcf.gz to get .tbi file
Finally, I run truvari bench -b sv.vcf.gz -c all.vcf.gz -f chr.fa -o tru

ERROR:root:No SAMPLE columns found in vcf (sv.vcf.gz)
ERROR:root:No SAMPLE columns found in vcf (all.vcf.gz)
Couldn't run Truvari. Please fix parameters

I get this ERROR, how can I solve it?

**Comment by ACEnglish** [comment]
We've documented common challenges with using VCFs on the [wiki](https://github.com/spiralgenetics/truvari/wiki) with a [link](https://github.com/acenglish/usable_vcf) to a tool that can help you validate your files.
To answer your question directly, it seems you probably want to check your header where you'll see no sample column defined in the VCF.

**Comment by azure-twilight** [comment]
Thanks, I see the VCF file have no Sample column, but how to add the sample column? Is there a tool to fix the VCFs?

**Comment by ACEnglish** [comment]
I do not have a tool to fix the VCFs, nor do I know of any that does this. It's a fairly simple process, though so you'll only need to make a script that parses the VCF and adds the columns.
