### ISSUE TITLE
Compatibility with GRIDSS output

### ISSUE THREAD

**Issue by stan-maine** [spiralgenetics/truvari#72]
I have had a lot of trouble benchmarking with output from GRIDSS. I have put one of the lines of the gridss ouput vcf below to understand what the issues are. The gridss file runs but then all 55000 variants show up as FPs because it says "No TP or FP calls in comp!". I think the issue is that gridss uses breakpoint annotation instead of svtype. Is there a way I can convert this so I can benchmark these variants? I tried outputting only what I thought truvari needed but I end up with an error before it completes that says "IndexError: invalid sample index". I have put that input below as well. Let me know what I can do so that I can benchmark these variants. Thank you for your help.

GRIDSS VCF format annotated with simple type (returns with "No TP or FP calls in comp!" error):
chr1	54775	gridss0fb_45o	C	CTTCTTTC[chr1:54783[	1578.56	PASS	AS=1;ASC=1X;ASQ=621.85;ASRP=1;ASSR=41;BA=0;BANRP=0;BANRPQ=0;BANSR=0;BANSRQ=0;BAQ=0;BASRP=0;BASSR=0;BEID=asm0-167330,asm0-200;BEIDH=0,0;BEIDL=0,0;BMQ=57.91;BMQN=37;BMQX=60;BQ=222.14;BSC=11;BSCQ=222.14;BUM=0;BUMQ=0;BVF=5;CAS=0;CASQ=0;CQ=925.7;EVENT=gridss0fb_45;IC=18;IHOMPOS=0,0;IQ=506.71;MATEID=gridss0fb_45h;MQ=48.45;MQN=25;MQX=60;RAS=1;RASQ=450;REF=96;REFPAIR=38;RP=0;RPQ=0;SB=0.46052632;SC=131M1X;SR=0;SRQ=0;SVLEN=0;SVTYPE=BND;VF=26;SIMPLE_TYPE=INS	GT:ASQ:ASRP:ASSR:BANRP:BANRPQ:BANSR:BANSRQ:BAQ:BASRP:BASSR:BQ:BSC:BSCQ:BUM:BUMQ:BVF:CASQ:IC:IQ:QUAL:RASQ:REF:REFPAIR:RP:RPQ:SR:SRQ:VF	.:621.85:1:41:0:0:0:0:0:0:0:222.14:11:222.14:0:0:5:0:18:506.71:1578.56:450:96:38:0:0:0:0:26

GRIDSS output less columns (returns "IndexError: invalid sample index"):
chr1    54775   gridss0fb_45o   C       <INS>   1578.56 PASS    END=54775;SVTYPE=INS;

Thanks,
Stanley

**Comment by ACEnglish** [comment]
Truvari does not work to match BND variants across SVTYPEs (e.g. interpreting two BNDs as either end of a DEL). As I'm not familiar with GRIDSS methodology or output, I can't advise specifically on how you should interpret the breakends to create resolved calls. However, I can say that one problem in the altered line is the columns do not match VCF expect columns. Each of the following columns would need to be present:

> #CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  SAMPLE

For more information on validating a VCF, see [the wiki](https://github.com/spiralgenetics/truvari/wiki#before-you-start)
