### ISSUE TITLE
Truvari running errors from Parliament2

### ISSUE THREAD

**Issue by daft-punkk** [spiralgenetics/truvari#75]
Dear Adam,
First of all, thank you so much for the great tool.
I need some technical advice for running Truvari from Parliament2 results.

There are six independent results;  
Running erros generated from **lumpy, delly** and **breakseq** VCF.

delly: format error
lumpy:  KeyError: 'unknown format: GQ'
breakdancer: format error

**manta, breakdancer, cnvnator,** these VCF files are working.

Do you have any ideas?

Thank you !

**Comment by ACEnglish** [comment]
We've documented common challenges with using VCFs on the [wiki](https://github.com/spiralgenetics/truvari/wiki) with a [link](https://github.com/acenglish/usable_vcf) to a tool that can help you validate your files.

Guessing from the errors you've posted here:
Breakdance / Delly : I'm not sure what's happening
Lumpy :  The header is probably missing a line like "##FORMAT=GQ.."

**Comment by daft-punkk** [comment]
Thank you so much!!
