### ISSUE TITLE
Incorrect results with multi-allelic records

### ISSUE THREAD

**Issue by ldenti** [spiralgenetics/truvari#88]
**Version** : 
Truvari v3.0.1

**Describe the bug** : 
When VCFs contains multi-allelic variations, truvari results are incorrect. It seems like truvari considers only the first allele of each record.

**To Reproduce** : 
Run truvari on the example data:
```
truvari bench -b base1.vcf.gz -c comp.vcf.gz -o out -f <hs37d5.fa> --passonly -r 1000 -p 0.00
```

**Expected behavior** : 
Results should be 2TPs while I'm getting 1TP and 1FP.

**Example Data** : 
[truvari-example-data.tar.gz](https://github.com/spiralgenetics/truvari/files/7539342/truvari-example-data.tar.gz)

**Additional context** :
If the base VCF contains:
```
1	249097709	.	A	<longallele1>,<longallele2>	...
```
and the comparison VCF contains:
```
1	249097709	.	A	<longallele1>	...
1	249097709	.	A	<longallele2>	...
```
truvari reports a TP and a FP (instead of 2TPs). This is the example I attached.

Similarly, if the base VCF contains:
```
1	249097709	.	A	G,<longallele>	...
```
and the comparison VCF contains:
```
1	249097709	.	A	<longallele>	...
```
then truvari reports just a FP (instead of a TP).

Currently, I solved the issue by splitting each multiallelic records in two separate records. But I think this shouldn't be considered the solution to this issue.

Best,
Luca

**Comment by ACEnglish** [comment]
Hello,

It is [documented](https://github.com/spiralgenetics/truvari/wiki/Multi-allelic-VCFs) that truvari expects VCF records to have single-allleles. You have implemented the correct solution. I considered implementing multi-allelic comparison but found it would have been more difficult and would create reporting complexities that also could have became tickets. 

Having said that, there may be ways I can raise logging warnings/errors when multi-allelic are encountered. Or I could better direct users' attention to that multi-allelic wiki page. Thank you for bringing this to my attention.

Have a great day,
~/Adam English
