### ISSUE TITLE
Low precision when using wf-human-sv

### ISSUE THREAD

**Issue by imdanique** [spiralgenetics/truvari#89]
Hello, I'm using wf-human-sv pipeline (https://github.com/epi2me-labs/wf-human-sv) to call SVs from a human genome sequenced with nanopore. The last step of the pipeline is truvari bench, which executes 
```bash
truvari bench --passonly --pctsim 0 -b $truthset_vcf -c $calls_vcf -f $reference -o $name --includebed $include_bed
```
I used HG002 as truthset. I am worried that I have low precision and f1 in the output:
![image](https://user-images.githubusercontent.com/56155720/145790204-9a0076a4-3f4b-4e6d-9942-1be91c199c51.png). How I can improve it, and what are the optimal numbers for a human genome sequenced with ONT?

**Comment by ACEnglish** [comment]
I've seen long-read sequencing accomplish 90%+ precision/recall/f1. 

If you'd like to debug Truvari, you can run it again with `--debug` for verbose logging which describes when/how SV are failing to find matches. You can also manually grab a False Negative from the `fn.vcf` and search it's position in your comparison VCF via `bcftools view -r chr?:start-end` where the coordinates are the region of the false negative ± some buffer. 

Truvari only analyzes the SV results as provided. Please feel free to reopen this issue with specific examples of matches that Truvari is failing to make or other specific errors the program is raising.  I'm unfamiliar with the `wf-human-sv` pipeline and if your debugging shows that Truvari is correctly reporting the calls not matching up, I'd suggest you open tickets with them.
