### ISSUE TITLE
ZeroDivisionError in /truvari/bench.py

### ISSUE THREAD

**Issue by stefmldk** [spiralgenetics/truvari#97]
**Version** : 
v.3.1.0

**Describe the bug** : 
ZeroDivisionError: float division by zero.

**A clear and concise description of what the bug is**:

The bug arises in /truvari/bench.py at line line 269, in calc_performance:
    100 * (float(self["TP-base"]) / (self["TP-base"] + self["FN"])))

**Expected behavior**:
The script already prints a warning if self["TP-base"] == 0 and self["FN"] == 0. When this condition is met, the above calculation should not happen, obviously, but it does.

A simple, tested fix would be to add an else statement before the  logging.info() call at line 267.

**Comment by ACEnglish** [comment]
Thank you for reporting this. I just removed that log line entirely. It was useful in the past when there was a time delay between knowing the recall and writing the report. But the recent speed refactors have that line useless.
